### DISCUSSION TITLE
Incorporating Supply Chain Files

### DISCUSSION THREAD

**Discussion by dtimm** [cloudfoundry/bosh#2466] [Ideas]
Hello Bosh Community,

I would like to propose a standard way to incorporate supply chain information for components into Bosh releases.

### Why
In the wake of supply-chain attacks including the one affecting [SolarWinds](https://en.wikipedia.org/wiki/2020_United_States_federal_government_data_breach), companies and governments have accelerated adoption of secure supply chain processes. One of the key requirements that underpins these efforts is collecting and maintaining records of where software components and their dependencies come from. This can include bills of materials, proof of code review, cryptographically signed attestations of build provenance, and many other forms of supply chain data. As a software packaging tool, Bosh has a privileged position in the supply chain, and it can facilitate the use of this data by standardizing its own approach to managing supply chain files.

### How
1) Introduce a `supply_chain` array at the top level of package spec files. It will be a list of file or file globs with formats. The supported formats will be `spdx+json`, `vnd.cyclonedx+json`, `vnd.syft+json`, and `vnd.in-toto+json`. `format` will use the [IANA names](https://www.iana.org/assignments/media-types/media-types.xhtml#application) where possible, dropping `application/`.
	
	Example `supply_chain` section for the `bpm` job of `bpm-release`:
	```yaml
	supply_chain:
	- name: bpm/sbom.spdx.json
	  format: spdx+json
    - name: bpm/*.attest.json
	  format: vnd.in-toto+json
	```
	The files will be stored in the `src/` directory and included in their package like items from the `files` list.
1) Add the `supply_chain` list with all globs expanded to the final `release.MF` section for each package under `packages`.

	Example `release.MF` excerpt:
	```yaml
	packages:
	- name: bpm
	  version: be375c78c703cea04667ea7cbbc6d024bb391182
	  fingerprint: be375c78c703cea04667ea7cbbc6d024bb391182
	  sha1: 6ae70da9768bd7333b883463e089c65bea44c685
	  dependencies:
	  - golang-1-linux
	  - bpm-runc
	  - tini
	  supply_chain:
	  - name: bpm/sbom.json
	    format: spdx+json
	  - name: bpm/build.attest.json
	    format: vnd.in-toto+json
	  - name: bpm/source.attest.json
	    format: vnd.in-toto+json
	```
This will allow downstream consumers of Bosh releases to easily access these files, and it will also ensure future enhancements to Bosh tooling (aggregating SBoMs, performing attestations directly, etc.) have a stable base to work from.
