### ISSUE TITLE
Specifying "latest" version and also directory path URL for release gives weird error during deploy

### ISSUE THREAD

**Issue by amitkgupta** [cloudfoundry/bosh#1044]
If I have the following in my manifest

```
release:
  - name: hello
    version: latest
    url: file:///path/to/release/dir
```

And I `bosh deploy`, I get an error like:

```
Cannot find file `/var/folders/3z/st02pqt10q7fx_s715rxxwqr0000gn/T/d20151128-13417-1bojzdd/d20151128-13417-1i5h4o3/release.MF'
```

I think it should either use `latest` and ignore the `url` information, or fail with an informative error message, saying that you can't specify "latest" version and also specify a URL simultaneously for a release.  I think the latter is better UX, but I'm not sure what is easier to implement in the CLI codebase.  What would be the best solution here?  Happy to try and submit a PR.
