### ISSUE TITLE
How to deploy software in multiple clusters

### ISSUE THREAD

**Issue by yyl8815** [cloudfoundry/bosh#1049]
Hi there,
I am trying to deploy CloudFoundry onto vshpere.

I have two clusters which are planed for Z1 and Z2. In z1 cluster, I have two host: first and second, while in z2 cluster, i have one host: third. I have attached nfs disk for each of the three host: nfs_first, nfs_second and nfs_third.

Below is part of my manifest of my bosh(I deploy both with bosh-init):
```
    vcenter: &vcenter # <--- Replace values below
      address: 10.32.102.234:4430
      user: administrator
      password: Dangerous!
      datacenters:
      - name: cf
        vm_folder: vm_folder
        template_folder: template_folder
        datastore_pattern: 'nfs_*'
        persistent_datastore_pattern: 'nfs_*'
        disk_path: director_disk
        clusters: [cf_z1, cf_z2]

```

As you can see, I have added two clusters to my director. However, when I try to deploy bosh, it reports below error:
```
  Waiting for the agent on VM 'vm-a2350078-b959-466a-974e-61ccfe8c7cbf' to be re             ady... Finished (00:00:46)
  Attaching disk 'disk-3e9876fd-03b6-4c88-a696-8d8ac240e606' to VM 'vm-a2350078-             b959-466a-974e-61ccfe8c7cbf'... Failed (00:00:02)
Failed deploying (00:02:58)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Updating instance disks:
        Updating disks:
          Deploying disk:
            Attaching disk in the cloud:
              CPI 'attach_disk' method responded with error: CmdError{"type":"Un             known","message":"Datastore 'nfs_first' is not accessible to cluster 'cf_z1'","o             k_to_retry":false}

```

What's the problem? Am I doing anything wrong?
