### ISSUE TITLE
bosh download manifest adds exclamation marks ! 

### ISSUE THREAD

**Issue by jszroberto** [cloudfoundry/bosh#1056]
Hi everyone,  

I have issues with spruce because when I download a manifest from the director, it contains exclamation marks in places I haven't added them when uploading it. 

What I have uploaded: 
```
   route_registrar:      
      routes:     
      - name: uaa     
        port: 8080
        tags:     
          component: uaa    
        uris:
        - uaa.fabric.lon.bluemix.net      
        - '*.uaa.fabric.lon.bluemix.net' 
```

What I download: 

```
properties: 
    route_registrar:
      routes:
      - name: uaa
        port: 8080
        tags:
          component: uaa
        uris:
        - uaa.fabric.ng.bluemix.net
        - ! '*.uaa.fabric.ng.bluemix.net'

```
What can I do to avoid bosh adding those exclamations marks? 

I have an issue open also in the spruce project: https://github.com/geofffranks/spruce/issues/75

Thanks in advance.
