### ISSUE TITLE
`reuse_compilation_vms: true` breaks `workers` limit in `compilation`

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1108]
Steps to reproduce:
* specify a `compilation` section in your deployment manifest like this
```
compilation:
  workers: 2
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: c1.medium
    availability_zone: us-east-1c
```
* deploy something with many packages to compile, e.g. Cloud Foundry

expected:
* at most 2 compilation VMs are active at any given time

actual:
* More compilation VMs are created

Note:
* If `reuse_compilation_vms` is set to `false` everything works as expected.

**Comment by cunnie** [comment]
@voelzmo , We were unable to reproduce your problem. Perhaps you could send us a redacted manifest  and the version of BOSH Director (e.g. release 250) you were using? We were using release 250.

We had the following stanza in our test release:
```
compilation:
  workers: 2
  network: cf_private
  reuse_compilation_vms: true
  cloud_properties:
    availability_zone: us-east-1c
    instance_type: c3.large
```

And during our deploy (of CF) only 2 compilation VMs were spun up (expected behavior, not buggy behavior):

```
bosh -t xxxx vms
Acting as user 'admin' on 'xxxx'
Deployment `cf'

Director task 8

Task 8 done

+-------------------------------------------------------------------------------------------+---------+-----+---------+--------------+
| VM                                                                                        | State   | AZ  | VM Type | IPs          |
+-------------------------------------------------------------------------------------------+---------+-----+---------+--------------+
| compilation-656d3bb9-2b4e-4513-bb26-e1f78e82918d/0 (e216d84e-47bf-424a-87da-5faf578e3b4f) | running | n/a |         | 10.10.130.11 |
| compilation-d22dc122-423d-4f1d-8f63-fac1f1bf229f/0 (1d4ae658-0f16-49b8-b1d3-9f6c99052f1f) | running | n/a |         | 10.10.130.10 |
+-------------------------------------------------------------------------------------------+---------+-----+---------+--------------+

VMs total: 2
```

We created an integration test to specifically expose this type of problem, although we only committed to a branch not to *develop* or *master*: 
https://github.com/cloudfoundry/bosh/tree/compilation-112544589
