### ISSUE TITLE
BOSH does not show an error for non-existent security group in AWS

### ISSUE THREAD

**Issue by qanx** [cloudfoundry/bosh#1116]
We recently encountered an issue where a security group hadn't been created before running a BOSH deployment. Once we realized this, we created the security group and redeployed "successfully", but it turned out the group still hadn't been successfully applied. We ended up needing to delete and (re-)deploy the deployment. Can BOSH be updated to:

* Error when given a non-existent group
* Correctly identify if a security group was not successfully applied

Environment information:

Using BOSH version 1.3177.0 with AWS.

Some additional background for reproducing:

```
networks:
- name: shield-net
  subnets:
  - cloud_properties:
      security_groups:
      - shield-admin
      - fake-sg
      subnet: subnet-xxxxxxxx
    dns:
    - x.y.z.2
    gateway: x.y.z.1
    name: default_unused
    range: x.y.z.0/24
    reserved:
    - x.y.z.2 - x.y.z.244
    static:
    - x.y.z.245
  type: manual
```

This networking configuration in the deployment deploys without error, and logging into AWS and looking at the EC2 instance shows only the `shield-admin` group (the security group that exists). After creating the `fake-sg` security group and redeploying with `bosh deploy` and `bosh deploy --recreate` the security group does not appear to be associated with the EC2 instance. Only `bosh delete deployment` and `bosh deploy` cause the newly deployed instance to associate with the `fake-sg` group.
