### ISSUE TITLE
Job links do not appear to work according to documentation

### ISSUE THREAD

**Issue by craigfurman** [cloudfoundry/bosh#1118]
I'm using director v246, and following the [job links documentation](https://github.com/cloudfoundry/bosh-notes/blob/master/links.md).

I have the following jobs in my manifest (truncated for clarity):
```
  - name: broker
    templates:
      - name: broker
        release: redis-on-demand-broker
        provides:
          broker: {as: b}

  - name: register-broker
    lifecycle: errand
    templates:
      - name: register-broker
        release: redis-on-demand-broker
        consumes:
          broker: {from: b}
```

broker spec:
```
provides:
- {name: broker, type: broker}
```

register-broker errand spec:
```
requires:
  - {name: broker, type: broker}
```

control script in register-broker errand:
```
<%
Kernel.p link('broker')
raise 'I only want to see the output of the line above'
%>
```

The error I get is:
```
Error filling in template `errand.sh.erb' for `register-broker/0' (line 6: Can't find link 'broker') (00:00:00)

Error 100: Error filling in template `errand.sh.erb' for `register-broker/0' (line 6: Can't find link 'broker')
```

I had a brief look through the public tracker and codebase, and tried changing "consumes" to "requires" in both the manifest and the register-broker errand spec. I then got a different error:
```
Link path was not provided for required link 'broker' in job 'register-broker' (00:00:00)

Error 140014: Link path was not provided for required link 'broker' in job 'register-broker'
```
