### ISSUE TITLE
Redacting properties in diffs only works for **either** job.properties **or** global properties

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1122]
Using bosh_cli and director in version v250
### Steps to reproduce
- Deploy [dummy-boshrelease](https://github.com/pivotal-cf-experimental/dummy-boshrelease) with the following manifest

```

---
name: dummy
director_uuid: <your UUID>
releases:
  - name: dummy
    version: latest

networks:
  - name: default
    type: manual
    subnets:
      - <your subnet here>

jobs:
  - name: dummy_with_properties_z1
    template: dummy_with_properties
    instances: 1
    resource_pool: small_pool
    networks:
      - name: default
    properties:
      network_name: default
      echo_value: "is someone here?"

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: small_2_2
    availability_zone: <your AZ>

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 3000-600000
  update_watch_time: 5000-600000

resource_pools:
  - name: small_pool
    network: default
    stemcell:
      name: bosh-openstack-kvm-ubuntu-trusty-go_agent
      version: "3140"
    cloud_properties:
      availability_zone: <your AZ>
      instance_type: small_2_2
properties:
  what:
    is:
      going:
        on: here
```
- On the first deploy, all `properties` are redacted
- Change the global `properties.what.is.going.on` to something different
- start `bosh deploy` and see that the global property is redacted, but _don't_ deploy yet! Cancel instead.
- Additionally change the local `jobs.dummy_with_properties_z1.properties.echo_value`
- start `bosh deploy` and see that the global property is no longer redacted, only the local one.
### Screenshots
- Redacting the global diff only works
  <img width="684" alt="screen shot 2016-02-01 at 10 38 51" src="https://cloud.githubusercontent.com/assets/2256887/12713621/0544a180-c8d0-11e5-874b-c23cc891c68b.png">
- Redacting local and global doesn't work
  <img width="636" alt="screen shot 2016-02-01 at 10 38 27" src="https://cloud.githubusercontent.com/assets/2256887/12713635/15d4612a-c8d0-11e5-8ed7-e16dd04ecafa.png">
### Additional Easteregg
- the property string `on` seems to be translated to `true` in the diff, even if it is a key, not a value.

**Comment by cppforlife** [comment]
Associated story: https://www.pivotaltracker.com/story/show/112825405

**Comment by wcamarao** [comment]
@voelzmo we're getting this fixed for the local vs global level of properties to be redacted, but we're unsure whether the easter egg part means another issue. To clarify, is the key change from "on" to "true" unexpected?

Thanks,
Wagner & @yuzhangcmu

**Comment by voelzmo** [comment]
@wcamarao yup, the rename seems weird an unexpected to me. Not sure why this happens, though. Fun fact: once you deployed successfully with the key being changed from `on` to `true`, it is impossible to update this deployment. The director tries to calculate a diff on the boolean `true`, which leads to a stacktrace.

So yes, I'd say the rename should not happen. Maybe this is too much of an edge-case to invest much effort in it, so depending on how hard it is to fix, I would decide. :)

**Comment by wcamarao** [comment]
@voelzmo thanks for confirming. After looking into the yaml spec, I don't think we should do something about this. Here's why:

1- Both keys and values in yaml are nodes, meaning keys are not strings ([node spec](http://www.yaml.org/spec/1.2/spec.html#id2764044)). So, keys could be a boolean for example, in any of its representations. Keys are still expected to be unique but interestingly, keys such as `yes` and `on` would result in duplicate keys - read on. :)
2- Yaml booleans could also be represented as a few different English words ([bool type](http://yaml.org/type/bool.html)), e.g. `on`/`off`, `yes`/`no`.

This part of the issue seems more related to yaml itself, so I'd suggest that when needed, we wrap such keywords in quotes so they're not evaluated as boolean and instead treated as string. Aye?

**Comment by wcamarao** [comment]
We investigated further the deployment always failing after changing key from `on` to `true` and we weren't able to reproduce it. Any more details you can provide to help reproduce it + a stacktrace?

**Comment by voelzmo** [comment]
@wcamarao making sure that the keys are strings seems to make sense to me.

Some steps to reproduce what I described above:
* deploy the above manifest with global properties looking like this:
```
properties:
  what:
    is:
      going:
        on: here
```

Note: I saw the deploy fail with recent stemcells with this error
```
Error 100: undefined method `to_sym' for true:TrueClass
```

However, I was experimenting with older stemcells at that point, and e.g. with v3140 I could actually deploy it. Maybe due to another ruby version?
