### ISSUE TITLE
unresponsive agent VMs deployed from child BOSH

### ISSUE THREAD

**Issue by subhankarc** [cloudfoundry/bosh#1123]
I have BOSH-lite deployed on my local machine and I have deployed `bosh deploy` BOSH using the following mainfest.

```

---
name: microbosh

director_uuid: 35b3e645-7b07-435a-bfab-69f718e0e8ef

releases:
- {name: bosh,            version: 244}
- {name: bosh-warden-cpi, version: latest}
- {name: garden-linux,    version: latest}

jobs:
- name: bosh
  instances: 1
  templates:
  - {name: nats, release: bosh}
  - {name: redis, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: postgres, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: warden_cpi, release: bosh-warden-cpi}
  - {name: garden, release: garden-linux}
  resource_pool: default
  persistent_disk: 8_000
  networks:
  - {name: default, static_ips: [10.244.9.2]}
  cloud_properties:
   cpu: 1
   ram: 512
   disk: 1_000


properties:
  ntp: ["0.us.pool.ntp.org"]

  nats:
    address: 127.0.0.1
    user: nats
    password: admin

  blobstore:
    address: 127.0.0.1
    port: 25251
    backend_port: 25552
    agent: {user: agent, password: admin}
    director: {user: director, password: admin}

  postgres: &db
    host: 127.0.0.1
    port: 5432
    user: bosh
    password: admin
    database: bosh

  redis:
    address: 127.0.0.1
    password: admin

  director:
    name: bats
    address: 10.244.9.2
    encryption: false
    backend_port: 25556
    endpoint: https://10.244.9.2:25556
    enable_snapshots: true
    cpi_job: warden_cpi
    db: *db

    # Compatibility with current garden networking manifest config
    ignore_missing_gateway: true

  hm:
    http:
      port: 25923
      user: admin
      password: admin
    director_account:
      user: admin
      password: admin
    intervals:
      poll_director: 60
      poll_grace_period: 30
      log_stats: 300
      analyze_agents: 60
      agent_timeout: 180
      rogue_agent_alert: 180
    loglevel: info
    email_notifications: false
    tsdb_enabled: false
    cloud_watch_enabled: false
    resurrector_enabled: true

  # cpi job template
  warden_cpi:
    host_ip: 10.244.9.2
  #  loopback_range: [100, 130]
    warden:
      connect_network: tcp
      connect_address: 127.0.0.1:7777
    actions:
      stemcells_dir: "/var/vcap/data/warden_cpi/stemcells"
      disks_dir: "/var/vcap/store/warden_cpi/disks"
      host_ephemeral_bind_mounts_dir: "/var/vcap/data/warden_cpi/ephemeral_bind_mounts_dir"
      host_persistent_bind_mounts_dir: "/var/vcap/data/warden_cpi/persistent_bind_mounts_dir"
    agent:
      mbus: nats://nats:admin@10.244.9.2:4222
      blobstore:
        provider: dav
        options:
          endpoint: http://10.244.9.2:25251
          user: agent
          password: admin


  # garden job template
  garden:
    listen_network: tcp
    listen_address: 0.0.0.0:7777
    disk_quota_enabled: false
    allow_host_access: true
    # todo expecting fix for this from garden team
    mount_btrfs_loopback: false

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties:
   cpu: 1
   ram: 512
   disk: 1_000

networks:
- name: default
  type: manual
  subnets:
  - range: 10.244.9.0/30
    reserved: [10.244.9.1]
    static: [10.244.9.2]
    cloud_properties: {}
- name: compilation
  type: dynamic
  cloud_properties: {}

compilation:
  workers: 5
  network: compilation
  cloud_properties:
   ram: 2048
   disk: 6_000
   cpu: 1

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000 - 90000
  update_watch_time: 5000 - 15000
```

Now I tried to target this bosh director using `bosh target 10.244.9.2` .

In this new director I can upload stemcell, upload release and then try to deploy a release. It works successfully. But after few minutes, the VMs of this deployment done from the new director becomes  unresponsive.

```
$ bosh vms
Deployment `redis-warden'

Director task 80

Task 80 done

+-----------------+--------------------+---------------+-----+
| Job/index       | State              | Resource Pool | IPs |
+-----------------+--------------------+---------------+-----+
| unknown/unknown | unresponsive agent |               |     |
| unknown/unknown | unresponsive agent |               |     |
| unknown/unknown | unresponsive agent |               |     |
| unknown/unknown | unresponsive agent |               |     |
| unknown/unknown | unresponsive agent |               |     |
+-----------------+--------------------+---------------+-----+

```

Can someone help me with this if I am missing something here ?

Regards,
Subhankar
