### ISSUE TITLE
Question: How to generate sha1 for release/stemcell/cpi packages?

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#1146]
How to generate sha1 manually for existing release/stemcell/cpi packages?

For examples:

```
releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=255.3
  sha1: 1a3d61f968b9719d9afbd160a02930c464958bf4
- name: bosh-openstack-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=23
  sha1: 94fc3b5f72fec737c5ccba223dc5622d8eca4b5d

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent?v=3012
    sha1: e92f3bd5081301652005bdc3dd11bff545a304ef
```

Thanks.
