### ISSUE TITLE
Getting error after updating BOSH director and CF: undefined method `deep_merge' for ["uaa"]:Array

### ISSUE THREAD

**Issue by allomov** [cloudfoundry/bosh#1179]
Hey, all.

We updated BOSH director from 3033 (193) to 3215 (255.5). After that we tried to migrate CF from version 192 to 233 and got the following error:
```
[2016-03-22 18:04:38 #8042] [] DEBUG -- Director: (0.000142s) SELECT * FROM "stemcells" WHERE ("name" = 'bosh-aws-xen-hvm-ubuntu-trusty-go_agent')
E, [2016-03-22 18:04:38 #8042] [] ERROR -- Director: NoMethodError - undefined method `deep_merge' for ["uaa"]:Array:
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/manifest/changeset.rb:21:in `initialize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/manifest/changeset.rb:43:in `new'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/manifest/changeset.rb:43:in `block in diff'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/manifest/changeset.rb:32:in `each_pair'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/manifest/changeset.rb:32:in `diff'
```
You can see [complete log here](https://gist.github.com/allomov-altoros/575c1cf172b6aef30ec5).

The problem occurred in [changeset.rb](https://github.com/cloudfoundry/bosh/blob/stable-3215/bosh-director/lib/bosh/director/manifest/changeset.rb#L21) file that tried to compute diff between manifests of current deployment and the new manifest. The problem is that old version of CF had the following consul properties in manifest:
```
- instances: 1
  name: uaa_z2
  networks:
  - name: cf2
  properties:
    consul:
      agent:
        services:
        - uaa
```
and the newest version of cf-release switched to using hash instead of array in the [following way](https://github.com/cloudfoundry/cf-release/blob/v233/example_manifests/minimal-aws.yml#L120-L124):
```
- instances: 1
  name: uaa_z1
  networks:
  - name: cf1
  properties:
    consul:
      agent:
        services:
          uaa: {}
```
As far as I can see, the BOSH fails to find manifest changes when array is substituted with hash.

Possible solution in this case is to:

1. remove consul from initial deployment, 
2. deploy this manifest
3. update the manifest to use newest version of cf-release
4. deploy it
