### ISSUE TITLE
BOSH addons can't deploy same release

### ISSUE THREAD

**Issue by longnguyen11288** [cloudfoundry/bosh#1180]
BOSH can't deploy same release if used in addons. I'm trying to use addons for my metrics boshrelease and having releases with same name/version isn't allowed.

Metrics Deployments
```
compilation:
  cloud_properties:
    name: random
  network: metrics1
  reuse_compilation_vms: true
  workers: 6
director_uuid: 17a45148-1d00-43bc-af28-9882e5a6535a
jobs:
- instances: 1
  name: metrics_z1
  networks:
  - name: metrics1
    static_ips:
    - 10.244.8.2
  persistent_disk: 4096
  properties:
    grafana:
      admin_password: password
      admin_username: admin
    influxdb:
      database: metrics
      host: 10.244.8.2
      password: password
      username: admin
  resource_pool: small_z1
  templates:
  - name: grafana
    release: metrics
  - name: influxdb
    release: metrics
name: metrics-warden
networks:
- name: metrics1
  subnets:
  - gateway: 10.244.8.1
    name: metrics1
    range: 10.244.8.0/24
    static:
    - 10.244.8.2-10.244.8.60
  type: manual
properties: {}
releases:
- name: metrics
  version: 2
resource_pools:
- cloud_properties:
    name: random
  name: small_z1
  network: metrics1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-30000

```

Addon.yml
```
releases:
- name: metrics
  version: 2

addons:
- name: metrics
  jobs:
  - name: telegraf
    release: metrics
  properties:
    influxdb:
      database: metrics
      host: 10.244.8.2
      password: password
      username: admin
```

Output
```
$ bosh -n deploy
Acting as user 'admin' on deployment 'metrics-warden' on 'Bosh Lite Director'
Getting deployment properties from director...

Detecting deployment changes
----------------------------
releases:
- name: metrics
  version: 2
addons:
- name: metrics
  jobs:
  - name: telegraf
    release: metrics
  properties:
    influxdb:
      database: "<redacted>"
      host: "<redacted>"
      password: "<redacted>"
      username: "<redacted>"

Deploying
---------

Director task 13
  Started preparing deployment > Preparing deployment. Failed: Runtime manifest specifies release `metrics' with version as `2'. This conflicts with version `2' specified in the deployment manifest. (00:00:00)

Error 530003: Runtime manifest specifies release `metrics' with version as `2'. This conflicts with version `2' specified in the deployment manifest.

Task 13 error

For a more detailed error report, run: bosh task 13 --debug
```
