### ISSUE TITLE
 bosh cck recreates a vm in a partitioned network

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/bosh#1182]
We're experiencing network partitioning when using the `bosh cck` command on AWS, when the instance has been terminated from under the bosh director. This issue came to our attention while using `turbulence` in our [acceptance test suite](https://github.com/cloudfoundry-incubator/etcd-release/blob/993cbd05329a6281d79e401687c4501367479c9f/src/acceptance-tests/turbulence/kill_vm_test.go#L58), but the same behavior can be reproduced if you terminate an instance from the EC2 instance dashboard.

We've seen this happen inconsistently, but since we've upgraded to BOSH 255.5 it happens more frequently.

BOSH director version: 255.5
BOSH-AWS-CPI version: 46
bosh cli: 1.3215.0

1) deploy etcd.yml

```
director_uuid: SOME_DIRECTOR_UUID
name: etcd
compilation:
  cloud_properties:
    availability_zone: us-east-1a
    ephemeral_disk:
      size: 1024
      type: gp2
    instance_type: m3.medium
  network: etcd1
  reuse_compilation_vms: true
  workers: 3
update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-180000
networks:
- name: etcd1
  subnets:
  - cloud_properties:
      name: ""
      subnet: SOME_SUBNET
    gateway: 10.0.16.1
    range: 10.0.16.0/24
    reserved:
    - 10.0.16.2-10.0.16.3
    - 10.0.16.12-10.0.16.254
    static:
    - 10.0.16.4
    - 10.0.16.5
    - 10.0.16.6
    - 10.0.16.7
    - 10.0.16.8
  type: manual
resource_pools:
- name: etcd_z1
  network: etcd1
  cloud_properties:
    availability_zone: us-east-1a
    ephemeral_disk:
      size: 1024
      type: gp2
    instance_type: m3.medium
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
jobs:
- instances: 3
  name: etcd_z1
  networks:
  - name: etcd1
    static_ips:
    - 10.0.16.4
    - 10.0.16.5
    - 10.0.16.6
  persistent_disk: 1024
  resource_pool: etcd_z1
  templates:
  - name: etcd
    release: etcd
properties:
  etcd:
    advertise_urls_dns_suffix: etcd.service.cf.internal
    heartbeat_interval_in_milliseconds: 50
    machines:
    - 10.0.16.4
    - 10.0.16.5
    - 10.0.16.6
    peer_require_ssl: false
    require_ssl: false
releases:
- name: etcd
  version: latest
```

2) ssh into etcd_z1/0 and ping etcd_z1/1

```
root@6f065e16-bcdd-4d39-9607-ceb7ca9ea6f4:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 0e:97:b6:d6:54:75
          inet addr:10.0.16.4  Bcast:10.0.16.255  Mask:255.255.255.0
          inet6 addr: fe80::c97:b6ff:fed6:5475/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:24247 errors:0 dropped:0 overruns:0 frame:0
          TX packets:23859 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:7481634 (7.4 MB)  TX bytes:2259136 (2.2 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:740 errors:0 dropped:0 overruns:0 frame:0
          TX packets:740 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:86657 (86.6 KB)  TX bytes:86657 (86.6 KB)

root@6f065e16-bcdd-4d39-9607-ceb7ca9ea6f4:~# ping 10.0.16.5
PING 10.0.16.5 (10.0.16.5) 56(84) bytes of data.
64 bytes from 10.0.16.5: icmp_seq=1 ttl=64 time=0.565 ms
64 bytes from 10.0.16.5: icmp_seq=2 ttl=64 time=0.337 ms
64 bytes from 10.0.16.5: icmp_seq=3 ttl=64 time=0.351 ms
^C
--- 10.0.16.5 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 0.337/0.417/0.565/0.106 ms 
```

etcd_z1/0 is able to successfully ping etcd_z1/1

3) ssh into etcd_z1/1 and ping etcd_z1/0

```
root@999209f0-f2b4-45b1-8925-d589e38d55c3:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 0e:03:0d:f9:de:77
          inet addr:10.0.16.5  Bcast:10.0.16.255  Mask:255.255.255.0
          inet6 addr: fe80::c03:dff:fef9:de77/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:27670 errors:0 dropped:0 overruns:0 frame:0
          TX packets:30574 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:7733678 (7.7 MB)  TX bytes:2826873 (2.8 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:872 errors:0 dropped:0 overruns:0 frame:0
          TX packets:872 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:106425 (106.4 KB)  TX bytes:106425 (106.4 KB)

root@999209f0-f2b4-45b1-8925-d589e38d55c3:~# ping 10.0.16.4
PING 10.0.16.4 (10.0.16.4) 56(84) bytes of data.
64 bytes from 10.0.16.4: icmp_seq=1 ttl=64 time=0.620 ms
64 bytes from 10.0.16.4: icmp_seq=2 ttl=64 time=0.537 ms
64 bytes from 10.0.16.4: icmp_seq=3 ttl=64 time=0.704 ms
64 bytes from 10.0.16.4: icmp_seq=4 ttl=64 time=0.414 ms
^C
--- 10.0.16.4 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3000ms
rtt min/avg/max/mdev = 0.414/0.568/0.704/0.111 ms
```

etcd_z1/1 is able to successfully ping etcd_z1/0

4) Terminate etcd_z1/0 in the EC2 instance dashboard

5) run bosh cck against the etcd deployment, and recreate the VM

```
$ bosh cck etcd
Performing cloud check...

Director task 27127
  Started scanning 3 vms
  Started scanning 3 vms > Checking VM states. Done (00:00:16)
  Started scanning 3 vms > 2 OK, 0 unresponsive, 1 missing, 0 unbound. Done (00:00:00)
     Done scanning 3 vms (00:00:16)

  Started scanning 3 persistent disks
  Started scanning 3 persistent disks > Looking for inactive disks. Done (00:00:17)
  Started scanning 3 persistent disks > 3 OK, 0 missing, 0 inactive, 0 mount-info mismatch. Done (00:00:00)
     Done scanning 3 persistent disks (00:00:17)

Task 27127 done

Started     2016-03-23 17:13:17 UTC
Finished    2016-03-23 17:13:50 UTC
Duration    00:00:33

Scan is complete, checking if any problems found...

Found 1 problem

Problem 1 of 1: VM with cloud ID `i-92b90009' missing.
  1. Skip for now
  2. Recreate VM for 'etcd_z1/0 (0dfe7e26-adf1-4178-8dc2-df285845b86b)'
  3. Delete VM reference
Please choose a resolution [1 - 3]: 2

Below is the list of resolutions you've provided
Please make sure everything is fine and confirm your changes

  1. VM with cloud ID `i-92b90009' missing.
     Recreate VM for 'etcd_z1/0 (0dfe7e26-adf1-4178-8dc2-df285845b86b)'

Apply resolutions? (type 'yes' to continue): yes
Applying resolutions...

Director task 27128
  Started applying problem resolutions > missing_vm 5299: Recreate VM for 'etcd_z1/0 (0dfe7e26-adf1-4178-8dc2-df285845b86b)'. Done (00:02:46)

Task 27128 done

Started     2016-03-23 17:14:03 UTC
Finished    2016-03-23 17:16:49 UTC
Duration    00:02:46
Cloudcheck is finished
```

6) ssh into etcd_z1/0 and ping etcd_z1/1

```
root@57387c87-ae62-4c9f-bda0-da949f2eb89a:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 0e:62:85:95:a4:0b
          inet addr:10.0.16.4  Bcast:10.0.16.255  Mask:255.255.255.0
          inet6 addr: fe80::c62:85ff:fe95:a40b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:974 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1604 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:5600016 (5.6 MB)  TX bytes:131520 (131.5 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:627 errors:0 dropped:0 overruns:0 frame:0
          TX packets:627 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:73016 (73.0 KB)  TX bytes:73016 (73.0 KB)

root@57387c87-ae62-4c9f-bda0-da949f2eb89a:~# ping 10.0.16.5
PING 10.0.16.5 (10.0.16.5) 56(84) bytes of data.
^C
--- 10.0.16.5 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4032ms
```

etcd_z1/0 cannot communicate with etcd_z1/1

7) ssh into etcd_z1/1 and ping etcd_z1/0

```
root@999209f0-f2b4-45b1-8925-d589e38d55c3:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 0e:03:0d:f9:de:77
          inet addr:10.0.16.5  Bcast:10.0.16.255  Mask:255.255.255.0
          inet6 addr: fe80::c03:dff:fef9:de77/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:27670 errors:0 dropped:0 overruns:0 frame:0
          TX packets:30574 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:7733678 (7.7 MB)  TX bytes:2826873 (2.8 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:872 errors:0 dropped:0 overruns:0 frame:0
          TX packets:872 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:106425 (106.4 KB)  TX bytes:106425 (106.4 KB)

root@999209f0-f2b4-45b1-8925-d589e38d55c3:~# ping 10.0.16.4
PING 10.0.16.4 (10.0.16.4) 56(84) bytes of data.
^C
--- 10.0.16.4 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4031ms
```

etcd_z1/1 cannot communicate with etcd_z1/0

As you can see, after we run `bosh cck` against our deployment, the terminated VM can no longer communicate to the other VMs in it's subnet.

We also confirmed that when `etcd_z1/0` comes back online, it is in the proper subnet and security group.
