### ISSUE TITLE
the 2nd security group is not applied to VM

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry/bosh#1272]
I have a deployment manifest like this
```
compilation:
  cloud_properties:
    instance_type: t2.small
  network: default
  reuse_compilation_vms: true
  workers: 6
director_uuid: daaaaabb-eeaa-aaaa-bbbb-abded5ad79ed
disk_pools:
- cloud_properties:
    type: gp2
  disk_size: 102400
  name: registry
jobs:
- instances: 1
  name: registry
  networks:
  - default:
    - dns
    - gateway
    name: default
  - name: elastic
    static_ips: aa.bb.cc.dd
  persistent_disk_pool: registry
  properties:
    docker:
      proxy:
        backend:
          hosts:
          - 127.0.0.1
        ssl:
          cert: |
            -----BEGIN CERTIFICATE-----
            -----END CERTIFICATE-----
          key: |
            -----BEGIN RSA PRIVATE KEY-----
            -----END RSA PRIVATE KEY-----
  resource_pool: small_z1
  templates:
  - name: registry
    release: docker-registry
  - name: proxy
    release: docker-registry
name: docker-registry-aws-ec2
networks:
- name: default
  subnets:
  - cloud_properties:
      security_groups: [bosh, docker-registry]
      subnet: subnet-c5da0ab3
    dns:
    - 10.0.4.2
    gateway: 10.0.4.1
    range: 10.0.4.0/24
    reserved:
    - 10.0.4.2 - 10.0.4.10
  type: manual
- cloud_properties: {}
  name: elastic
  type: vip
properties: {}
releases:
- name: docker-registry
  version: latest
resource_pools:
- cloud_properties:
    instance_type: t2.small
    root_disk:
      size: 10240
      type: gp2
  name: small_z1
  network: default
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-30000
```

After it's deployed, I notice 2 issues here:

1. But after the job is deployed, only "bosh" security group is applied to VM.
I didn't see "docker-registry" on that VM.

2. In my case, I want to use gp2 disk type instead of "standard" one. After job is deployed, I notice there 3 disks attached:
```
vol-29d5b69b  	100 GiB 	gp2  		/dev/sdf
vol-36284684  	10 GiB		standard	/dev/sdb
vol-1d2846af	10 GiB		gp2			/dev/xvda
```
the 2 gp2 are expected, but where does 10GiB(standard) come from?
And how can I change it to gp2 if I need that?

My bosh version is 
```
$ bosh -v
BOSH 1.3232.0
```
