### ISSUE TITLE
"Error 160006: Static IP `...' is out of network `default' range" is misleading

### ISSUE THREAD

**Issue by michaellihs** [cloudfoundry/bosh#1291]
I had an error in my deployment manifest:

```
networks:
  - name: default
    type: manual
    subnets:
      - cloud_properties: {}
        range: 10.244.1.0/24
        reserved:
          - 10.244.1.1
        static:
          - 10.244.1.5
          - 10.244.1.5

...

jobs:
  - name: job1
    ...
    networks:
      - name: default
        static_ips:
          - 10.244.1.5

  - name: job2
    ...
    networks:
      - name: default
        static_ips:
          - 10.244.1.5
```

where I accidentally used the same IP twice for two VMs and also defined a wrong set up static IPs.

The error message I got was

```
Error 160006: Static IP `10.244.1.5' is out of network `default' range
```

I guess that something like

```
Static IP `10.244.1.5` assigned to job `job2` is already taken by job `job1`
```

would be more helpful when trying to debug the problem.
