### ISSUE TITLE
[Feature request] Share properties between jobs(monit daemons) within the same VM

### ISSUE THREAD

**Issue by liuweichu** [cloudfoundry/bosh#1343]
As a example, when deploying

```
jobs:
- name: hm9000
  templates:
  - name: daemon1
    release: x-release
  - name: daemon2
    release: y-release
...
```

and in `y-release/jobs/daemon2/spec`, there are properties defined as:

```
properties:
  daemon2.p1:
    default: ...
```

Previously (with older bosh director), when bosh director templating daemon1's erb files, it can see the value of `daemon2.p1`. But now seems it's "fixed" as a bug.

However, such behavior is very convenience for some of the use case such as doing properties dumping inside VM, so that as PaaS admin we can quickly investigate what value is set in a certain VM. For me, it's more natural to think jobs inside the same VM should share properties when templating. But now it is almost impossible to share properties unless in daemon1's job spec file we define all `daemon2.*` properties beforehand.

I want to know why this is regarded as a bug, and is there a way to implement properties sharing easily?

Thank you
