### ISSUE TITLE
BOSH misreports the offending job template when releases using the same packages are colocated in an instance group

### ISSUE THREAD

**Issue by aditya87** [cloudfoundry/bosh#1392]
We tried to deploy cf-release 240 with routing-release 0.136.0, and we got the following error:
```
Error 80011: Package name collision detected in instance group 'cloud_controller': job 'routing/routing-api' depends on package 'routing/routing_utils', job 'cf/go-buildpack' depends on 'cf/routing_utils'. BOSH cannot currently collocate two packages with identical names from separate releases.
```
Our instance group looks like follows:
```
- name: cloud_controller
  azs:
  - first-az
  instances: 1
  lifecycle: service
  jobs:
  - name: consul_agent
    release: consul
    consumes: {}
    provides: {}
  - name: go-buildpack
    release: cf
    consumes: {}
    provides: {}
  - name: binary-buildpack
    release: cf
    consumes: {}
    provides: {}
  - name: nodejs-buildpack
    release: cf
    consumes: {}
    provides: {}
  - name: ruby-buildpack
    release: cf
    consumes: {}
    provides: {}
  - name: php-buildpack
    release: cf
    consumes: {}
    provides: {}
  - name: python-buildpack
    release: cf
    consumes: {}
    provides: {}
  - name: java-offline-buildpack
    release: cf
    consumes: {}
    provides: {}
  - name: staticfile-buildpack
    release: cf
    consumes: {}
    provides: {}
  - name: cloud_controller_ng
    release: cf
    consumes: {}
    provides: {}
  - name: routing-api
    release: routing
    consumes: {}
    provides: {}
  - name: metron_agent
    release: cf
    consumes: {}
    provides: {}
  - name: route_registrar
    release: cf
    consumes: {}
    provides: {}
  - name: statsd-injector
    release: cf
    consumes: {}
    provides: {}
```

route_registrar is the template that refers to `cf/routing_utils`, not `go-buildpack`. We think this is because of a bug in this loop:
https://github.com/cloudfoundry/bosh/blob/28001bdcbf4e6d31ab153139f54b8047de71deb6/bosh-director/lib/bosh/director/deployment_plan/instance_group.rb#L263

BOSH should report the right offending template, which in this case would be route_registrar.
