### ISSUE TITLE
Cannot delete settings for 'i-079c327bbf01ffcba', got HTTP 401

### ISSUE THREAD

**Issue by blade2005** [cloudfoundry/bosh#1414]
When trying to run a deploy i get this error above.

I've looked in the postgre db and see that the instance is in the db but only some of the fields are filled in.

```
select * from instances
19 | al_agent-nodes | 0 | 2 | | started | f | 893127d2-594f-441a-8fbd-7cb4471354bc | | | f | t | | | | | | da39a3ee5e6b4b0d3255bfef95601890afd80709 | f | f
```

```
Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 42
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Done (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started compiling packages > al_agent/26a166d5c63db8332e96b77d52e322d78232b961. Failed: Cannot delete settings for 'i-079c327bbf01ffcba', got HTTP 401 (00:00:22)

Error 100: Cannot delete settings for 'i-079c327bbf01ffcba', got HTTP 401
```

https://github.com/cloudfoundry/bosh/blob/master/bosh-registry/lib/bosh/registry/api_controller.rb#L32-L36

However the registry std*.log don't show the requests hitting registry daemon.

**Comment by cppforlife** [comment]
@blade2005 this typically means your registry auth configuration is mismatched. ensure that cpi's and registry's auth matches up.

**Comment by blade2005** [comment]
Hrm it should all match up.

I redeployed with the passwords all being the same and it still failed with 401.


```
---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.3
  sha1: e4442afcc64123e11f2b33cc2be799a0b59207d0
- name: bosh-aws-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=57
  sha1: cbc7ed758f4a41063e9aee881bfc164292664b84

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3262.8
    sha1: 48ca720f4c458cfbdbf83732d9349c9e8beee6b8
  cloud_properties:
    instance_type: m3.xlarge
    ephemeral_disk: {size: 25_000, type: gp2}
    availability_zone: us-west-2a

disk_pools:
- name: disks
  disk_size: 20_000
  cloud_properties: {type: gp2}

networks:
- name: private
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns: [10.0.0.2]
    cloud_properties: {subnet: subnet-bfc8bac9}
- name: public
  type: vip

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: aws_cpi, release: bosh-aws-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [10.0.0.6]
    default: [dns, gateway]
  - name: public
    static_ips: [PUBLICIP]

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: PASSWORD__1

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: PASSWORD__1
      database: bosh
      adapter: postgres

    registry:
      address: 10.0.0.6
      host: 10.0.0.6
      db: *db
      http: {user: admin, password: PASSWORD__1, port: 25777}
      username: admin
      password: admin
      port: 25777

    blobstore:
      address: 10.0.0.6
      port: 25250
      provider: dav
      director: {user: director, password: PASSWORD__1}
      agent: {user: agent, password: PASSWORD__1}

    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: aws_cpi
      max_threads: 10
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: PASSWORD__1}
          - {name: hm, password: PASSWORD__1}

    hm:
      director_account: {user: hm, password: PASSWORD__1}
      resurrector_enabled: true

    aws: &aws
      access_key_id: XXXXXXXXXXXXXXXXXXXX
      secret_access_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      default_key_name: bosh
      default_security_groups: [bosh]
      region: us-west-2

    agent: {mbus: "nats://nats:nats-password@10.0.0.6:4222"}

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: aws_cpi, release: bosh-aws-cpi}

  ssh_tunnel:
    host: PUBLICIP
    port: 22
    user: vcap
    private_key: ./bosh.pem

  mbus: "https://mbus:mbus-password@PUBLICIP:6868"

  properties:
    aws: *aws
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
```

At one point I dumped the config from the bosh-registry daemon and tried to find registry passwords in the bosh-director config that would tell it how to connect to bosh-registry.

I followed instructions from here for the deploy of the bosh/0 https://bosh.io/docs/init-aws.html

Should my individual deploy of services include the registry password or not?

This deploy is taking place in AWS. I looked at the auth for registry daemon and the AWS secret id/key match. 

How can I check what information the bosh-director is using to authenticate to the bosh-registry?

**Comment by dpb587-pivotal** [comment]
I see you changed `registry.http.password` - you should also make sure to update `registry.password` with the same value. The AWS CPI client uses `registry.password`, but the registry server uses `registry.http.password`.

**Comment by blade2005** [comment]
To make sure I'm clear on this. So under the aws section

```
properties:
  aws:
    registry
      password: PASSWORD__1
```
or is the correct update this
```
properties:
  registry:
    password: PASSWORD__1
    http:
      password: PASSWORD__1
```

Or am I not quite understanding where I need to put registry.password?

**Comment by blade2005** [comment]
Alright I see where I was missing it

```
jobs:
- name: bosh
  properties:
    registry:
      address: 10.0.0.6
      host: 10.0.0.6
      db: *db
      http: {user: admin, password: PASSWORD__1, port: 25777}
      username: admin
      password: PASSWORD__1
      port: 25777
```

I had
```
jobs:
- name: bosh
  properties:
    registry:
      address: 10.0.0.6
      host: 10.0.0.6
      db: *db
      http: {user: admin, password: PASSWORD__1, port: 25777}
      username: admin
      password: admin
      port: 25777
```

Why is it that bosh requires me to set the same password twice for the same block of properties?
