### ISSUE TITLE
Failed to create S3 object, access_key_id and secret_access_key must be provided

### ISSUE THREAD

**Issue by blade2005** [cloudfoundry/bosh#1442]
This issue seems similar to https://github.com/cloudfoundry/bosh/issues/494

I am using https://github.com/cloudfoundry/bosh-sample-release.git with some additions of  my own to add in a piece of software.

This is the command I executed
```
$ bosh upload release releases/wordpress/wordpress-5.yml
```

This is the error I got
```
Uploading release
wordpress-5.t:  96% |oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo         |  61.6MB 737.3KB/s ETA:  00:00:03
Director task 15
  Started extracting release > Extracting release. Done (00:00:00)

  Started verifying manifest > Verifying manifest. Done (00:00:00)

  Started resolving package dependencies > Resolving package dependencies. Done (00:00:00)

  Started creating new packages
  Started creating new packages > nginx/2c3c37b95f97597077540cd8d0e9edd95b6afc52. Failed: Failed to create S3 object, code 1, output: '', error: '2016/09/16 19:42:31 access_key_id and secret_access_key must be provided
' (00:00:00)

Error 100: Failed to create S3 object, code 1, output: '', error: '2016/09/16 19:42:31 access_key_id and secret_access_key must be provided
'

Task 15 error
wordpress-5.t:  96% |oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo         |  61.8MB 715.6KB/s Time: 00:01:28

For a more detailed error report, run: bosh task 15 --debug
```

This is an AWS env.

final.yml
```
--- 
final_name: wordpress
min_cli_version: 1.0.3
blobstore: 
  provider: s3
  options: 
    bucket_name: pst-cf-wordpress
```

private.yml
```
---
blobstore:
  s3:
    access_key_id: [redacted]
    secret_access_key: [redacted]
```

**Comment by blade2005** [comment]
Bucket is set to region for oregon. I updated my final.yml file to reflect that

```
--- 
final_name: wordpress
min_cli_version: 1.0.3
blobstore: 
  provider: s3
  options:
    region: us-west-2
    endpoint: https://s3-us-west-2.amazonaws.com
    bucket_name: pst-cf-wordpress
```

Still go the same error.
