### ISSUE TITLE
bosh delete deployment failing and got stuck while deleteing dea-spare.

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry/bosh#1453]
I am using bosh-init bosh-257.9 ,bosh-openstack-cpi-27,stemcell 3262.2. and cf233.I am able to deploy cloudfoundry.
when i try to delete it it gets stuck at dea-spare.Here i have 3 dea-spare vm outwhich one got deleted, but remaining two still there.
however all other VMs got deleted.I am getting this problem repeatedly.
I use following command to delete deployment.

`bosh -n delete deployment cf-mydeployment --force`

Please help me fix this issue.how can i debug issue.

![image](https://cloud.githubusercontent.com/assets/16615487/18872468/3a603e8c-84d8-11e6-8639-8b0d5b44ee76.png)

job output

![image](https://cloud.githubusercontent.com/assets/16615487/18872558/b4670abc-84d8-11e6-8af7-5be113d2f7d2.png)

```
- instances: <%= $dea_instances %>
  name: dea-spare
  networks:
  - name: dea-spare-net
  properties:
    consul:
      agent:
        services:
          dea:
            check:
              interval: 5m
              name: dns_health_check
              script: /var/vcap/jobs/dea_next/bin/dns_health_check
              status: passing
    dea_next:
      zone: 'zone'
    metron_agent:
      zone: 'zone'
  resource_pool: dea-spare-xlarge
  templates:
  - name: consul_agent
    release: cf
  - name: dea_next
    release: cf
  - name: dea_logging_agent
    release: cf
  - name: metron_agent
    release: cf
  update:
    serial: false
    max_in_flight: 5

```
