### ISSUE TITLE
Feature request:  Director can leverage private S3 compatible blobstore

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/bosh#1455]
For private cloud deployments, it would be usefull to be able to leverage private s3 compatible solution. (in our case, we have a private Scality s3 provider).

These requires to be able to set the private S3 endpoint in bosh.yml

**Comment by kitsirota** [comment]
+1 We ran into this very recently also.  

It would be great if we could also store director compiled assets on S3 to speed up bosh director updates and deployments.

**Comment by voelzmo** [comment]
This should be already possible. We're using Dreamhost in a few test runs. Make sure your `blobstore` property in the bosh-init manifest looks like this:
```
blobstore:
        provider: s3
        access_key_id: <redacted>
        secret_access_key: <redacted>
        bucket_name: <redacted>
        host: objects.dreamhost.com
```

**Comment by voelzmo** [comment]
@kitsirota storing the compiled packages in S3 is also possible using [`compiled_package_cache`](http://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=257.15#p=compiled_package_cache):
```
    compiled_package_cache:
      options:
        access_key_id: <redacted>
        bucket_name: <redacted>
        s3_force_path_style: true
        secret_access_key: <redacted>
      provider: s3
```
