### ISSUE TITLE
S3 Blobstore in read only mode ignores advanced configs

### ISSUE THREAD

**Issue by johnsonj** [cloudfoundry/bosh#1462]
# Background
When no credentials are provided and no endpoint is set, the `S3BlobstoreClient` will create a `SimpleBlobstoreClient` based off of the bucket name and the default endpoint (`S3BlobstoreClient::ENDPOINT`). This ignores any options that would be used when credentials are set (`host, use_ssl, port`).

# Repro
Given `config/fnal.yaml`:
```yaml
---
final_name: example-app
blobstore:
  provider: s3
  options:
    bucket_name: my-gcp-bucket
    host: storage.googleapis.com
    use_ssl: false
```
## Expected
Blobstore attempts to fetch from: `http://storage.googleapis.com/my-gcp-bucket/`
## Actual
Blobstore attempts to fetch from: `https://s3.amazonaws.com/my-gcp-bucket/`
