### ISSUE TITLE
`bosh stop` detects deployment changes 

### ISSUE THREAD

**Issue by Kiemes** [cloudfoundry/bosh#1474]
If you are using a deployment with version `latest` for either release or stemcell in the manifest, the diff algorithm will complain about deployment changes when calling `bosh stop`.

```
$ bosh stop
Acting as user 'admin' on deployment 'dummy' on 'my-bosh'
You are about to stop all jobs

Detecting deployment changes
----------------------------
Releases
No changes

Compilation
No changes

Update
No changes

Resource pools
No changes

Disk pools
No changes

Networks
No changes

Jobs
No changes

Properties
No changes

Stemcells
No changes

Instance groups
No changes

Cannot perform job management when other deployment changes are present. Please use '--force' to override.
```

Deployment manifest extract:

```
releases:
- name: dummy
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest
```

This diff algorithm should not complain if `latest` is used as version value, either for release or for stemcell.

This was tested with the current ruby bosh cli 1.3262.4.0
