### ISSUE TITLE
In Fog code integrated in bosh-cpi, the check of “response.get_header('Content-Type') == 'application/json'” lead to failure in CF deployment 

### ISSUE THREAD

**Issue by zhutao11** [cloudfoundry/bosh#1495]
**Version:**
```
releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.14
  sha1: b41821dccee78ad7bd44466cd0160920c183787a
- name: bosh-openstack-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=27
  sha1: 85e6244978f775c888bbd303b874a2c158eb43c4
```

**Issue**
In Fog code ,such as Line 391 of '/var/vcap/packages/registry/gem_home/ruby/2.3.0/gems/fog-openstack-0.1.7/lib/fog/openstack/compute.rb' in Bosh-director,
a check of ' if !response.body.empty? && response.get_header('Content-Type') == 'application/json''
is here

If the HTTP Reponse Header is "Content-Type"=>"application/json; **charset=UTF-8**", the CF deployment will fail

**Will the next Bosh-cpi solve this problem,or intergate a Fog version without this check?**
