### ISSUE TITLE
Support source code diffs between deployments

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/bosh#1525]
This issue is a proposal for discussion rather than a concrete feature request:

Sometimes it is incredibly helpful to troubleshoot an issue by knowing what has changed since the last deployment. While it is kind of possible to track down such changes with the information provided by BOSH, it's difficult and error prone.

I can imagine different scenarios what a real use case could look like.

**Proposal 1:**
```
$ bosh diff deployment 2345 2346
Deployment changes
----------------------------
Releases
etcd
  version type changed: String -> Fixnum
    - 86
    + 86

Properties
cc
  bits_service
    + enabled: true
    + password: blahblahblahbblah
    + private_endpoint: http://bits-service.service.cf.internal
    + public_endpoint: http://bits-service.cf1.bits.cf-app.com
    + username: admin


Release changes
------------------

bits-service 0.0.234 -> 0.0.252:
https://github.com/cloudfoundry-incubator/bits-service-release/compare/1a59a892f42f946d7181a738c84e69af786c9f5f...b88a79d26c9df7070ed6e305a6b06fb056eafef3

```

**Proposal 2:**

```
$ bosh diff deployment 2345 2346
Deployment changes
----------------------------
///// snip. same as above

Release changes
--------------------

bits-service 0.0.234 -> 0.0.252:
jobs/bits-service/spec
@@ -157,15 +157,27 @@ properties:
bits-service.nginx.access_log_destination:
description: "Nginx access log destination. Can be used to route access logs to a file, syslog, or a memory buffer."
- default: "/var/vcap/sys/log/nginx_bits/nginx.access.log"
+ default: "/var/vcap/sys/log/nginx_bits/access.log"
+ bits-service.nginx.public_access_log_destination:
+ description: "Nginx access log destination. Can be used to route access logs to a file, syslog, or a memory buffer."
+ default: "/var/vcap/sys/log/nginx_bits/public_access.log"
+ bits-service.nginx.private_access_log_destination:
+ description: "Nginx access log destination. Can be used to route access logs to a file, syslog, or a memory buffer."
+ default: "/var/vcap/sys/log/nginx_bits/private_access.log"
```

**Thoughts on implementation**

To make this possible, a few things would be necessary in BOSH:
1. Don't just capture a commit sha in a BOSH release, but also the source it was generated from, e.g. the URL to a github repo. This could simply be an optional parameter to `bosh create release` or it could be deduced automatically from git remote.
2. Attach an id to each deployment (it's unclear to me from the `bosh events` output if this already exists anyways). These ids can then be used in `bosh diff deployment <id1> <id2>`.
3. When each deployment knows its release versions, then the above proposals should be straightforward to implement.

Any thoughts or comments on these proposals?

**Comment by cppforlife** [comment]
> Don't just capture a commit sha in a BOSH release, but also the source it was generated from, e.g. the URL to a github repo. This could simply be an optional parameter to bosh create release or it could be deduced automatically from git remote.

make sense.

> Attach an id to each deployment (it's unclear to me from the bosh events output if this already exists anyways). These ids can then be used in bosh diff deployment <id1> <id2>.

each event in the event log has ids.

> When each deployment knows its release versions, then the above proposals should be straightforward to implement.

it's definitely possible, not easy though. you may also would have to record entire manifest, cloud-config, etc in the events if you want to see that as part of diffing. if you are just referring to release diffing for now then we already record release version information in the events.

**Comment by petergtz** [comment]
> it's definitely possible, not easy though. you may also would have to record entire manifest, cloud-config, etc in the events if you want to see that as part of diffing. if you are just referring to release diffing for now then we already record release version information in the events.

The original idea was indeed about release diffing, because I found it often tedious to track down changes I made in different releases and why they probably broke my integration tests. So yes, just this would already help a lot.

Recording entire manifests and cloud-config would be extremely powerful in the following scenarios: 
1. Production: fast development and an aggressive delivery strategy lead to multiple deployments a day. A bug in the code generates a ticket, but at the time the ticket is looked at new deployments have already taken place. The creation time of the ticket can be used to identify the state of a deployment.
2. Testing: Sometimes integration tests break not because of code changes, but because of manifest changes. Seeing what manifest changes broke or fixed tests can help a lot in troubleshooting. Concourse helps a lot here already, because we can print/store the manifest before making a deployment. However, sometimes during troubleshooting, it's necessary to do a manual deployment to try things out. Any such manual changes won't be tracked by Concourse. And from a conceptual level, while it's nice that Concourse can be used to store such information, I think BOSH is the right place.

So, is my understanding right, that these would be in general desirable features? Or are there potentially other issues (perhaps conceptually) in this proposal?

**Comment by petergtz** [comment]
@cppforlife, I've taken a closer look at this, and it seems that introducing a new table/model would make this possible. What I've been thinking about is the following:

Table: **deployment_instances** (for lack of a better name at this point)

| name              | type      | description                                                         |
|-------------------|-----------|---------------------------------------------------------------------|
| id                | serial    | This id could exposed to the user as *deployment id* just like *task ids* are exposed to the user for further actions. |
| deployment_id     | integer   | FK to deployment.                                                   |
| started_at        | timestamp | stores when the deployment was started                              |
| completed_at      | timestamp | stores when the deployment was completed                            |
| cloud_config_id   | integer   | identifies the cloud_config used for the deployment                 |
| manifest_text     | text      | stores the deployment manifest as JSON (or similar)                 |
| runtime_config_id | integer   | identifies the runtime_config used for the deployment               |

Table: **deployment_instances_release_versions**

|name|type|description|
|-------|------|----|
|id|serial||
|deployment_instance_id|integer| FK to deployment_instance|
|release_version_id|integer | FK to release_version|

The UpdateDeployment job could simply add a new entry to the deployment_instances table for every deployment and associate it with the corresponding deployment and release_versions. That way, all information about a specific deployment is captured.

With this kind of addition, a couple of interesting features could be implemented:
1. `bosh diff deployment <deployment_name> <deployment_instance_id1> <deployment_instance_id2>` as proposed in my original post.
2. `bosh deployment history <deployment_name>` would show past deployments.
3. `bosh rollback deployment <deployment_name> <target_deployment_instance_id>` would roll back to a previous deployment.

I think especially the last one would be an extremely compelling feature for BOSH and incredibly useful for any production environment.

**Comment by cppforlife** [comment]
@petergtz what do you think about relying on `events` table for such information lookup? regarding rollback command i would be interesting in seeing how to make `bosh -d name deploy manifest.yml` + `bosh events` command work together. 

roughly thinking about it, it could look something like this using new CLI (https://github.com/cloudfoundry/bosh-cli):

`bosh -d dep deploy <(bosh interpolate <(bosh event 123 --context) --path /before/manifest)`

for the above to work, director would have to save manifest to the event and CLI would have to expose context information via `--context` flag. regarding cloud config and runtime config, i'm not sure if it would make sense to use older versions, as you might have already changed iaas itself.

you can already look at the history of a deployment via `bosh -d dep events`, but we don't yet have diff functionality. i think recording entire contents of cloud configs, runtime configs, and deployment manifests within deployment update events would be a good start.

**Comment by petergtz** [comment]
@cppforlife 

> what do you think about relying on events table for such information lookup?

So far, I looked at `events` to be more like a log that simply describes what is going on. It can certainly be used to implement what I proposed, but it feels a bit like that would be a misuse of its actual purpose.

But to me, what's more important is that it seems
1. not type-safe, because you would have to store everything in the context and so you suddenly expect typed data in the context in form of certain formats (e.g. JSON) that must formally describe at least release names+versions and manifest.
2. not entirely right, because deployments to me are a first-class concept in BOSH (just like releases) and therefore deserves to get its own table I believe. Things like creating or deleting VMs to me is not on the same level, because from an abstracted perspective I'm not interested in these details.

`events` seemed to be write only by machine and read only by humans. A `deployment_instances` table on the other hand would be part of BOSH's fundamental business logic. BOSH would base actions and decisions on it. Again, this is how I looked at it.

> `bosh -d dep deploy <(bosh interpolate <(bosh event 123 --context) --path /before/manifest)`

While following the unix style of composing little functions with pipes into powerful commands, I'm a bit worried that such constructs are not very intuitive. One of the best things to me about BOSH is, that I don't have to think about a lot of the commands. Their naming and syntax just comes easy and naturally. The above doesn't follow that style.

> regarding cloud config and runtime config, i'm not sure if it would make sense to use older versions, as you might have already changed iaas itself.

Good point. I haven't worked enough with those two things, but if what you are saying is that the cloud config combined with the underlying IaaS config provides an abstraction layer that have to go hand in hand, but are ideally independent of the deployment manifest, then you're probably right, and cloud config shouldn't be rolled back. And after all, my understanding is that cloud config was extracted exactly for the reason that it changes much less frequently and hence, there is probably no good use case for rollbacks.

**Comment by cppforlife** [comment]
> It can certainly be used to implement what I proposed, but it feels a bit like that would be a misuse of its actual purpose.

I kind of agree; however, I think it might be useful to have first iteration for this feature to understand its upsides/downsides. Also should be cheaper to implement as MVP.

> not "type-safe"

well it could validated and so on. it's still in a db so we can run migrations and what not.

> ... Their naming and syntax just comes easy and naturally. The above doesn't follow that style.

agreed; however, that was more of a glue representation in its raw form. we can of course add commands to simplify commonly used interaction but underneath it would just use the same primitives.

**Comment by petergtz** [comment]
Everything you said makes sense.

**Comment by petergtz** [comment]
@cppforlife Out of curiousity, will this go into the tracker for BOSH, or what will be the next steps for this?

I could possibly implement this and submit a PR, but that would be in my private time, so this could take some time. Still, it sounds like a fun feature to work on.

**Comment by cppforlife** [comment]
@petergtz holidays took over... now back. feel free to give it a try implementing this. we are focusing right now dns, config server, and cliv2 so the queue is full at the moment. i typically only *try* to place stuff in tracker if they are going to happen in upcoming weeks.

**Comment by petergtz** [comment]
Started working on this here: https://github.com/petergtz/bosh/tree/add-deployment-revisions

A few simple cases already work. Complete integration tests are still missing and a lot of details. Will update this issue again, once I think it's ready to be reviewed.

**Comment by petergtz** [comment]
@cppforlife I gave this a first shot and I'd be happy if you could have a look at the [diff](https://github.com/cloudfoundry/bosh/compare/master...petergtz:add-deployment-revisions?expand=1).

A few notes:
* I debated long with myself if I should call the new entity `deployment_revision` or `audit_log_entry` (and similarly `history` versus `audit_log`). The latter would emphasize usefulness in contexts where precise audit_logs of production systems are required. OTOH, it's really different revisions of the same deployment. Suggestions welcome.
* I also debated with myself, if I should invent a completely new event type, or if I should simply formalize the existing deployment event. In the end, I decided for a new event type, as I feel like this is a first class concept, which I do not necessarily want to mix with the existing event structure.
* Using `object_name` as revision number is a bit hacky and I'm not super happy with it.
* The code comes only with a partially complete suite of tests just yet, but I can of course add them, should we decide to go forward with this.
* I have also not added CLI commands. Also waiting for feedback first.

**Some examples of its usage:**
* `curl -k 'https://test:test@localhost:61004/deployments/simple/history' | jq`

```yaml
[
  {
    "deployment_name": "simple",
    "revision_number": 4,
    "user": "test",
    "task": "7",
    "started_at": "2017-07-17 23:18:59 +0200",
    "completed_at": "2017-07-17 21:19:22 UTC",
    "error": null,
    "manifest_text": "---\nname: simple\ndirector_uuid: deadbeef\nreleases:\n- name: bosh-release\n  version: latest\nupdate:\n  canaries: 2\n  canary_watch_time: 4000\n  max_in_flight: 1\n  update_watch_time: 20\njobs:\n- name: foobar\n  templates:\n  - name: foobar\n  resource_pool: a\n  instances: 3\n  networks:\n  - name: a\n  properties: {}\n  persistent_disk_pool: disk_a\n"
  },
  {
    "deployment_name": "simple",
    "revision_number": 3,
    "user": "test",
    "task": "5",
    "started_at": "2017-07-17 23:18:44 +0200",
    "completed_at": "2017-07-17 21:18:53 UTC",
    "error": null,
    "manifest_text": "---\nname: simple\ndirector_uuid: deadbeef\nreleases:\n- name: bosh-release\n  version: 0.1-dev\nupdate:\n  canaries: 2\n  canary_watch_time: 4000\n  max_in_flight: 1\n  update_watch_time: 20\njobs:\n- name: foobar\n  templates:\n  - name: foobar\n  resource_pool: a\n  instances: 3\n  networks:\n  - name: a\n  properties: {}\n  persistent_disk_pool: disk_a\n"
  },
  {
    "deployment_name": "simple",
    "revision_number": 2,
    "user": "test",
    "task": "4",
    "started_at": "2017-07-17 23:18:32 +0200",
    "completed_at": "2017-07-17 21:18:41 UTC",
    "error": null,
    "manifest_text": "---\nname: simple\ndirector_uuid: deadbeef\nreleases:\n- name: bosh-release\n  version: 0.1-dev\nupdate:\n  canaries: 2\n  canary_watch_time: 4000\n  max_in_flight: 1\n  update_watch_time: 20\njobs:\n- name: foobar\n  templates:\n  - name: foobar\n  resource_pool: a\n  instances: 2\n  networks:\n  - name: a\n  properties: {}\n  persistent_disk_pool: disk_a\n"
  },
  {
    "deployment_name": "simple",
    "revision_number": 1,
    "user": "test",
    "task": "3",
    "started_at": "2017-07-17 23:18:18 +0200",
    "completed_at": "2017-07-17 21:18:28 UTC",
    "error": null,
    "manifest_text": "---\nname: simple\ndirector_uuid: deadbeef\nreleases:\n- name: bosh-release\n  version: 0.1-dev\nupdate:\n  canaries: 2\n  canary_watch_time: 4000\n  max_in_flight: 1\n  update_watch_time: 20\njobs:\n- name: foobar\n  templates:\n  - name: foobar\n  resource_pool: a\n  instances: 1\n  networks:\n  - name: a\n  properties: {}\n  persistent_disk_pool: disk_a\n"
  }
]
```

* `curl -k 'https://test:test@localhost:61004/deployments/simple/diff_revisions?revision1=3&revision2=4' | jq`

```yaml
{
  "manifest": [
    [
      "releases:",
      null
    ],
    [
      "- name: bosh-release",
      null
    ],
    [
      "  version: 0.1-dev",
      "removed"
    ],
    [
      "  version: latest",
      "added"
    ]
  ],
  "releases": {
    "added": [
      "bosh-release/0+dev.2"
    ],
    "removed": [
      "bosh-release/0.1-dev"
    ]
  }
}
```
