### ISSUE TITLE
"bosh download manifest" returns file that is different from its manifest

### ISSUE THREAD

**Issue by liuweichu** [cloudfoundry/bosh#1530]
We are on BOSH director v260.

Our manifest has all releases version and stemcell version as integer. For example 

```
- name: errand
  cloud_properties:
    availability_zone: ...
    instance_type: ...
  network: ...
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: 3215
```

However what we get from `bosh download manifest`, it becomes

```
- name: errand
  ...
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: '3215'
```

The same conversion is also seen at release version.

Such implicit conversion is confusing, because output manifest is not the same as input anymore.
