### ISSUE TITLE
onsite blobstore

### ISSUE THREAD

**Issue by warroyo** [cloudfoundry/bosh#1554]
is it possible to use something like Artifactory(supports webdav) as a blobstore for creating bosh releases?

**Comment by cppforlife** [comment]
@warroyo we have never used it, but you can try it and report back any errors.

**Comment by warroyo** [comment]
is there a way to use a generic blobstore like webdav? in the configs all i can find is documentation for s3 and atmos, or local. Im not sure I can try using artifactory if there is no way to configure it. 

can this be re-opened as a feature to add support for artifactory?

**Comment by warroyo** [comment]
ok, so i found that WEBDAV is supported(https://github.com/cloudfoundry/bosh/blob/c6c419f9eff844c35c8c7307e977427f05a23a51/src/bosh_cli/spec/assets/config/dav/config/final.yml). however there does not seem to be an option to ignore ssl verification when uploading the blobs. is there any way to do this? My artifactory uses a self signed cert.

**Comment by warroyo** [comment]
ok so I got this figured out. artifactory does work as on onsite blobstore. you have to use the webdav provider for the blobstore. also there is an option for ssl_verify_none that is not documented anywhere .

here are my configs:

final.yml

````
---
blobstore:
  provider: dav
  options:
    endpoint: https://myartifactory.com/artifactory/some-repo
    ssl_no_verify: true
final_name: my-release

````

private.yml

````
---
blobstore:
  dav:
    endpoint: https://myartifactory.com/artifactory/some-repo
    user: *********
    password: ********
````
