### ISSUE TITLE
Bosh::Clouds::VMCreationFailed' with message 'Server `4ccca6e9-5dd7-41da-8568-20469d3680d3' state is error, expected active

### ISSUE THREAD

**Issue by harshalk91** [cloudfoundry/bosh#1563]
Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 57
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Done (00:00:01)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started compiling packages
  Started compiling packages > cli/60a741596e7fc803f45c9628364b21d1b247550b
  Started compiling packages > nginx/8d0c80e9594988b792c1f83a8c1598a3f4d02b7a
  Started compiling packages > haproxy/f061c9f4854fab702991cf42653b9b09d711c9c1
  Started compiling packages > ruby-2.3/ca5b2d16eac54f907ab6c1f454d9c81560f311a2
  Started compiling packages > libmariadb/90d7836132e02bb570d91f08c9e116c394888d75
  Started compiling packages > dotnet-core-buildpack/dc2da8240e6831e5769ebab26340bb8ae3768630
   Failed compiling packages > ruby-2.3/ca5b2d16eac54f907ab6c1f454d9c81560f311a2: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'Server `4ccca6e9-5dd7-41da-8568-20469d3680d3' state is error, expected active
Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance 4ccca6e9-5dd7-41da-8568-20469d3680d3. Last exception: It is not allowed to create an interface on external network dc8385e3-3771-481d-ba98-4abf1f21c30b' in 'create_vm' CPI method (00:01:06)
   Failed compiling packages > cli/60a741596e7fc803f45c9628364b21d1b247550b: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'Server `624c8c2f-909f-400d-be25-7780b62d4a23' state is error, expected active
Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance 624c8c2f-909f-400d-be25-7780b62d4a23. Last exception: It is not allowed to create an interface on external network dc8385e3-3771-481d-ba98-4abf1f21c30b' in 'create_vm' CPI method (00:01:10)
   Failed compiling packages > libmariadb/90d7836132e02bb570d91f08c9e116c394888d75: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'Server `050e6c84-856f-45b6-95c4-be2b603f2ef3' state is error, expected active
Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance 050e6c84-856f-45b6-95c4-be2b603f2ef3. Last exception: It is not allowed to create an interface on external network dc8385e3-3771-481d-ba98-4abf1f21c30b' in 'create_vm' CPI method (00:01:10)
   Failed compiling packages > haproxy/f061c9f4854fab702991cf42653b9b09d711c9c1: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'Server `5bf1fbc6-75df-409c-b961-dfc7ad8d2473' state is error, expected active
Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance 5bf1fbc6-75df-409c-b961-dfc7ad8d2473. Last exception: It is not allowed to create an interface on external network dc8385e3-3771-481d-ba98-4abf1f21c30b' in 'create_vm' CPI method (00:01:12)
   Failed compiling packages > dotnet-core-buildpack/dc2da8240e6831e5769ebab26340bb8ae3768630: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'Server `f558b95c-0b1f-4482-8e61-a20423cabd9e' state is error, expected active
Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance f558b95c-0b1f-4482-8e61-a20423cabd9e. Last exception: It is not allowed to create an interface on external network dc8385e3-3771-481d-ba98-4abf1f21c30b' in 'create_vm' CPI method (00:01:13)
   Failed compiling packages > nginx/8d0c80e9594988b792c1f83a8c1598a3f4d02b7a: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'Server `cf2f444c-7988-4ed1-93f5-5f3124adb0d4' state is error, expected active
Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance cf2f444c-7988-4ed1-93f5-5f3124adb0d4. Last exception: It is not allowed to create an interface on external network dc8385e3-3771-481d-ba98-4abf1f21c30b' in 'create_vm' CPI method (00:01:14)

Error 100: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'Server `4ccca6e9-5dd7-41da-8568-20469d3680d3' state is error, expected active
Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance 4ccca6e9-5dd7-41da-8568-20469d3680d3. Last exception: It is not allowed to create an interface on external network dc8385e3-3771-481d-ba98-4abf1f21c30b' in 'create_vm' CPI method

```
---
director_uuid: e23b5aa1-d934-4176-a9c4-680c74c4b1f0

meta:
  environment: dev

  floating_static_ips:
  - 10.104.160.87
networks:
  - name: floating
    type: vip
    cloud_properties:
      net_id: dc8385e3-3771-481d-ba98-4abf1f21c30b
      security_groups: []
  - name: cf2
    type: manual
    subnets:
    - range: 192.168.1.0/24
      gateway: 192.168.1.1
      dns:
      - 10.19.1.23
      reserved:
      - 192.168.1.1 - 192.168.1.60
      static:
      - 192.168.1.61 - 192.168.1.254

      cloud_properties:
        net_id: ee216d00-1adb-4b00-a3f8-5d0a5514c142
        security_groups: ["cf"]

  - name: cf1
    type: manual
    subnets:
    - range: 10.104.160.0/20
      gateway: 10.104.160.1
      dns:
      - 10.19.1.23
      static:
      - 10.104.160.212
      - 10.104.160.240
      - 10.104.160.77
      - 10.104.160.81 - 10.104.160.97

      cloud_properties:
        net_id: dc8385e3-3771-481d-ba98-4abf1f21c30b
        security_groups: ["cf"]

```
