### ISSUE TITLE
BOSH update (260->261) failed with new stemcell (3312->3363)

### ISSUE THREAD

**Issue by antonsoroko** [cloudfoundry/bosh#1589]
Hi.

Old bosh.yml:
```
releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=260
  sha1: f8f086974d9769263078fb6cb7927655744dacbc
- name: bosh-openstack-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=27
  sha1: 85e6244978f775c888bbd303b874a2c158eb43c4

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent?v=3312
    sha1: 36dd5035c3868aa9f2da32291e6338636b63c345
```
New bosh.yml:
```
releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=261
  sha1: b7855edc33ece92e9e8e1b5d03c5e2c897d426d8
- name: bosh-openstack-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=30
  sha1: 2fff8e1c241a91267ddd099a553c1339d2709821

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent?v=3363
    sha1: 9db642b70eb93bb4092f967d8c1716be67af1a77
```

Error:
```
Started deploying
  Waiting for the agent on VM 'fd0e4139-f54f-467e-b91c-bd560d6ce057'... Finished (00:00:00)
  Stopping jobs on instance 'unknown/0'... Finished (00:00:01)
  Unmounting disk 'c21c7672-84b4-4fc5-8b4b-318cf2cb1557'... Finished (00:00:03)
  Deleting VM 'fd0e4139-f54f-467e-b91c-bd560d6ce057'... Finished (00:00:14)
  Creating VM for instance 'bosh/0' from stemcell '652416c5-b1f2-4449-835e-193e3d63831a'... Finished (00:01:09)
  Waiting for the agent on VM 'd9289248-2a87-425c-bd50-9d71c11fc965' to be ready... Finished (00:00:16)
  Attaching disk 'c21c7672-84b4-4fc5-8b4b-318cf2cb1557' to VM 'd9289248-2a87-425c-bd50-9d71c11fc965'... Failed (00:00:34)
Failed deploying (00:02:27)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Updating instance disks:
        Updating disks:
          Deploying disk:
            Mounting disk:
              Sending 'get_task' to the agent:
                Agent responded with error: Action Failed get_task: Task 46cb2187-932b-487d-4b42-aeeb4f47dabf result: Persistent disk with volume id 'c21c7672-84b4-4f
c5-8b4b-318cf2cb1557' could not be found
```

Actually, in openstack console and inside of VM I see that disk was attached, but was not mounted.
Unfortunately, the root password is not working in this half-upgraded VM, so I can't tell you more.

After the rollback to the previous version of the stemcell - update has been successfully completed.
