### ISSUE TITLE
bosh-registry: aws_credentials_provider should not be imported in registry.rb

### ISSUE THREAD

**Issue by AbelHu** [cloudfoundry/bosh#1621]
Even without setting `plugin`, bosh-registry still does not work with the error `uninitialized constant Bosh::Registry::AWS (NameError)`

I think that aws_credentials_provider should not be imported in [registry.rb](https://github.com/cloudfoundry/bosh/blob/master/src/bosh-registry/lib/bosh/registry.rb#L21) but should be imported in [config.rb](https://github.com/cloudfoundry/bosh/blob/master/src/bosh-registry/lib/bosh/registry/config.rb#L29)

**Comment by cppforlife** [comment]
@AbelHu how is this manifesting in an environment? how are you getting this error?

**Comment by AbelHu** [comment]
Execute the command `bin/bosh-registry -c reg.cfg`

reg.cfg
```

    ---
    loglevel: debug

    http:
      port: 25695
      user: admin
      password: admin

    db:
      database: "sqlite:///:memory:"
      max_connections: 32
      pool_timeout: 10
      adapter: sqlite
```
