### ISSUE TITLE
Director returns 500 error with malformed CloudConfig.yml

### ISSUE THREAD

**Issue by zaksoup** [cloudfoundry/bosh#1637]
With a cloud-config.yml that has the following networks section:

```
networks:
- name: transformers
  type: manual
  subnets:
  - range: 192.168.0/24
    reserved: []
    cloud_properties:
      name: wild-192.168.0
```

Note that our CIDR notation is missing a `.0`, i.e.:

```diff
+ - range: 192.168.0.0/24 
- - range: 192.168.0/24
```

The director returns a 500 error with no information:

```
Using environment '[zak's environment]' as client 'admin'

Continue? [yN]: y

Updating cloud config:
  Director responded with non-successful status code '500' response ''

Exit code 1
```

I would expect an error similar to the following:

```
Using environment '[zak's environment]' as client 'admin'

Continue? [yN]: y

Updating cloud config:
  Director responded with non-successful status code '400' response '{"code":40001,"description":"Required property 'range' did not describe a valid CIDR subnet"}'

Exit code 1
```

Filed by @zaksoup and @cunnie
