### ISSUE TITLE
Question about consuming a dynamic set of links [migrated from Gist]

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh#1649]
> Original question: [here](https://gist.github.com/Amit-PivotalLabs/c39528248b8cdc4ba8e347f8aa68abb6#gistcomment-2046092)
> Original asker: @claudio-benfatto

---

Hello @Amit-PivotalLabs thanks for the very helpful explanation.

We are actually facing a problem while trying to integrate `links` with one of our bosh releases and we think that our use case may not be fully covered by the current `links` functionalities.
I think it could be seen as a subcase of [What happens if multiple things provide the same type of link?](https://gist.github.com/Amit-PivotalLabs/c39528248b8cdc4ba8e347f8aa68abb6#what-happens-if-multiple-things-provide-the-same-type-of-link).

The specific problem is due to the fact that we do not know in advance, (referring to the examples in this document) the number of `database_instance` instance groups. 
At the same time we need to access them somehow dynamically from our configuration templates and specifically from the same instance group, something like the following:

```
instance_groups:
- name: web_server_instances
  jobs:
  - release: app
    name: web_server_process
    properties:
      greeting: "Namaste!"
    consumes:
      hindi_database_data_object_reference: {from: hindi_database}
      french_database_data_object_reference: {from: french_database}
```
```
<%
database_links = Array.new
database_links << link("hindi_database_data_object_reference")
database_links << link("french_database_data_object_reference")
%>

database_addresses={
<% database_links.each_with_index do |database, i| %>
  "<%= link("database").instances[0].address %>"<%= ',' if i < (database_links.size - 1) %>
<% end %>
}

```

but this ofc doesn't work very elegantly, for example, if we decided to add an `italian_database_data_object_reference: {from: italian_database}`, we would be forced to modify all the template files accordingly.

Would be really great to have something of this kind:

```
<%
database_links = link_by_type("database_data_class")
%>

database_addresses={
<% database_links.each_with_index do |database, i| %>
  "<%= link("database").instances[0].address %>"<%= ',' if i < (database_links.size - 1) %>
<% end %>
}

```

I have the feeling that we are missing something or trying to bend `links` functionalities a bit too much. Is there a better approach in order to achieve the same result?

Thanks a lot
Claudio
