### ISSUE TITLE
Links: Provide a hash & default values

### ISSUE THREAD

**Issue by hoegaarden** [cloudfoundry/bosh#1671]
## Problem

We have a job which `provides` many properties via a link. We don't want to specify each and every property on the `provides` block but have a whole hash be exposed via that link. What we found is that this generally works, however for properties *not* defined in the manifest, but only defined with a `default` in the job spec, the link does not expose that property.

## Example

providing job:
```yaml
provides:
- name: broker
  type: redis_broker
  properties:
  - redis.broker

properties:
  redis.broker.protocol:
    default: https
    description: fooo
  redis.broker.name:
    description: baar
  redis.broker.something:
    description: some description
    default: else
```

consuming job:
```yaml
consumes:
- { name: broker , type : redis_broker }
```

manifest:
```yaml
instance_groups:
- name: cf-redis-broker
  instances: 1
  jobs:
  - name: cf-redis-broker
    release: cf-redis
    properties:
      redis:
        broker:
          name: baz
```

With the above setup in the consuming job's template we see the following:
- `redis.broker.protocol` is not defined, although it has a default in the providing job's spec
- `redis.broker.name` is defined and has the value as configured in the manifest
- `redis.broker.something` is also not available

What we expect and would like to see:
- A hash something like:
```json
"redis" : {
  "broker" : {
    "protocol": "https",
    "name": "baz",
    "something": "else"
  }
}
```

## Questions

- Is this expected behaviour or did we hit some edge case?
- Would you be open for a PR which implements that properly?

**Comment by vlad-stoian** [comment]
Hi,

I've hit the exact same problem while working on RabbitMQ related links which have the same structure as @hoegaarden has explained above. My intuition was that I would get the default values in the hash, but they are missing, which means I have to use something similar to a `hash.fetch('key', default_value)`, which is not ideal, since one job has to **know** somehow the default value specified in the other job's spec.

I'm interested in the questions above as well.

**Comment by utako** [comment]
We've also hit this problem working on Release Engineering. Has there been any work done to address this? 

Thanks,
@utako and @davewalter

**Comment by cppforlife** [comment]
looks like the problem is related to specifying property groups (eg redis.broker) vs individual properties (eg redis.broker.protocol, etc.).

**Comment by ansd** [comment]
In this case, the provider is required to specify all individual properties like
```
provides:
- name: broker
  type: redis_broker
  properties:
  - redis.broker.protocol
  - redis.broker.name
  - redis.broker.something

properties:
  redis.broker.protocol:
    default: https
    description: fooo
  redis.broker.name:
    description: baar
  redis.broker.something:
    description: some description
    default: else
```
There should currently be no new feature which would allow the provider to specify the top-level property `redis.broker` only because that would be backwards-incompatible since existing deployments may relay on this existing behavior.
