### ISSUE TITLE
when specifying url and sha the version should not be required

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/bosh#1681]
When I specify a release in a deployment manifest with `url` and `sha1` that is enough information to validate what tarball to use.

Having the release require `version` with those properties can be confusing. If I don't specify `latest` it could be confusing that it goes to a different release tarball than the one specified in `url`.

For example:

```yaml
releases:
- name: datadog-agent
  url: https://github.com/onemedical/datadog-agent-boshrelease/releases/download/v5.8.5.5/datadog-agent-5.8.5.5.tgz
  sha1: fe8dc3e0a6dd058dfca81d2f927c3b93b4c92f80
  version: latest # why is this required?
```

This is the error that we got from the bosh deployment:

```
Processing release 'datadog-agent/':
  Expected version to be non-empty string

Exit code 1
```
