### ISSUE TITLE
Using `persistent_disk_fs: xfs` on GCP causes deployment to fail

### ISSUE THREAD

**Issue by tscolari** [cloudfoundry/bosh#1722]
When `env.persistent_disk_fs` is set to `xfs` on GCP, it causes the deployment to fail with this message:

```
13:26:19 | Error: Action Failed get_task: Task 976303a9-dd64-496d-6b5f-b959d2263eb3 result: Mounting persistent disk: Formatting partition with xfs: Shelling out to mkfs.xfs: Running command: 'mkfs.xfs /dev/sdb1', stdout: '', stderr: 'warning: device is not properly aligned /dev/sdb1
Use -f to force usage of a misaligned device
```

The relevant changes are:

```
persistent_disk: 10000
env:
  persistent_disk_fs: xfs
```

The same experiment works fine in AWS.

The  grootfs team is specially interested in this issue because this might impact some future feature requests where the ephemeral disk also could have and `xfs` option. (Grootfs tracker relevant story: https://www.pivotaltracker.com/story/show/147990209)

Here is a minimal bosh manifet to reproduce: (Note that the grootfs release is only used because it needs one, works with any release).
```
---                            
name: persistent-test          
stemcells:                     
- alias: trusty                
  os: ubuntu-trusty            
  version: latest              
releases:                      
  - name: grootfs              
    version: latest            
jobs:                          
- name: persistent-test        
  instances: 1                 
  vm_type: n1-standard-1       
  stemcell: trusty             
  lifecycle: service           
  persistent_disk: 10000       
  env:                         
    persistent_disk_fs: xfs    
  azs:                         
  - z1                         
  networks:                    
  - name: bosh-deployments     
  jobs:                        
    - name: grootfs            
      release: grootfs         
update:                        
  canaries: 1                  
  max_in_flight: 3             
  serial: false                
  canary_watch_time: 1000-240000                               
  update_watch_time: 1000-240000     
```

**Comment by cppforlife** [comment]
@cunnie thoughts?

**Comment by cunnie** [comment]
That's interesting.

I'd expect that to occur with an MBR-formatted disk but not a GPT formatted disk (for no other reasons than MBR is old and assumes 512byte sectors (which used to be all the rage in the seventies, eighties, and nineties)). Also there were often alignment problems (e.g. you wanted to have the partitions on a cylinder boundary, where Cylinders consisted of many Heads, and Heads were made up of Sectors) ("CHS") (A bad legacy of MBR).

A person who has a [similar problem](https://access.redhat.com/solutions/1374493) has an MBR disk formatted via `cfdisk` and fixed it by reformatting the drive with GPT via `parted`

**Comment by tscolari** [comment]
🆙 
Is there any update on this bug?

**Comment by dpb587-pivotal** [comment]
Can you provide the stemcell you're using? Also, does this happen every time?

**Comment by Callisto13** [comment]
hello @dpb587-pivotal @cunnie sorry we did not respond sooner.
I just quickly verified that the problem still exists, and yes it does seem to happen consistently.
Here is the simple manifest I was using:
```
---
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: garden
    properties:
      garden:
        debug_listen_address: 0.0.0.0:17013
        graph_cleanup_threshold_in_mb: 10240
        listen_address: 0.0.0.0:7777
        listen_network: tcp
        log_level: debug
    release: garden-runc
  name: garden
  networks:
  - name: default
  stemcell: stemcell
  vm_type: n1-standard-1
  persistent_disk: 10000
  env:
    persistent_disk_fs: xfs
name: xfs-persistent-test
releases:
- name: garden-runc
  version: 1.10.0
stemcells:
- alias: stemcell
  os: ubuntu-trusty
  version: '3468.17'
update:
  canaries: 1
  canary_watch_time: 1000-240000
  max_in_flight: 3
  update_watch_time: 1000-240000
```
and the error is still the same:
```
L Error: Action Failed get_task: Task a755a26d-196b-47a0-66b9-cb67f91405c8 result: Mounting persistent disk: Formatting partition with xfs: Shelling out to mkfs.xfs: Running command: 'mkfs.xfs /dev/sdb1', stdout: '', stderr: 'warning: device is not properly aligned /dev/sdb1
Use -f to force usage of a misaligned device
': exit status 1
```
