### ISSUE TITLE
Multiple CPI doesn't support intelligently select CPI during compilation

### ISSUE THREAD

**Issue by zhangtbj** [cloudfoundry/bosh#1789]
Hi,

I am trying multiple CPI, but I can only  set one az for complication, such as:

```
compilation:
  az: az_sl
  network: dynamic_az_sl
  reuse_compilation_vms: true
  vm_type: vm_az_sl
  workers: 6
```

The network and vm_type is only for one CPI, I think bosh needs to intelligently select CPI during compilation.

Thanks!
