### ISSUE TITLE
Optional BOSH-links consumption

### ISSUE THREAD

**Issue by AlbertoImpl** [cloudfoundry/bosh#1836]
Hi there!

We have a release and we are consuming a link that is optional:
`/jobs/deploy-service-broker/spec`:
```
consumes:
- name: credhub
  type: credhub
  optional: true
```
And in our tiles `handcraft.yml` we are consuming the link:
```
job_types:
- name: deploy-service-broker
  resource_label: Broker Deployer
  templates:
  - name: deploy-service-broker
    release: spring-cloud-broker
    consumes: |
      credhub: {from: credhub, deployment: "(( ..cf.deployment_name ))"}
  errand: true
```
If the link is provided everything works fine, but when is not there we are getting the `can't resolve link error`
```
Deploying
---------

Director task 772
  Started preparing deployment > Preparing deployment. Failed: Unable to process links for deployment. Errors are:
  - Can't resolve link 'credhub' in instance group 'deploy-service-broker' on job 'deploy-service-broker' in deployment 'p-spring-cloud-services-6e217903aead7d25732b'. Please make sure the link was provided and shared. (00:00:00)

Error 100: Unable to process links for deployment. Errors are:
  - Can't resolve link 'credhub' in instance group 'deploy-service-broker' on job 'deploy-service-broker' in deployment 'p-spring-cloud-services-6e217903aead7d25732b'. Please make sure the link was provided and shared.

Task 772 error
```

After some debugging with @pivotal-jamil-shamy this is working as intended: https://github.com/cloudfoundry/bosh/blob/5f3fd29ec9fda77667c959f1943bf3cfe5fcf656/src/spec/gocli/integration/links_spec.rb#L317-L331

However, our team will benefit if we could have optional links working with explicit linking.

**Comment by drnic** [comment]
I think you've accidentally got `consumes:` value as a string

```
consumes: |
      credhub: {from: credhub, deployment: "(( ..cf.deployment_name ))"}
```

Instead its an object:

```
consumes:
      credhub: {from: credhub, deployment: "(( ..cf.deployment_name ))"}
```

**Comment by AlbertoImpl** [comment]
Hi @drnic, thanks for the suggestion.
However, if I don't use it as a string I get the following error:

```
Cannot generate manifest for product Spring Cloud Services: failed to load YAML from {"credhub"=>{"from"=>"credhub", "deployment"=>"(( ..cf.deployment_name ))"}}: no implicit conversion of Hash into String
```

**Comment by drnic** [comment]
@AlbertoImpl I'm pretty sure this is a nuance of Pivotal Opsmgr Metadata (`consumes:` is not a string in a pure bosh manifest) Perhaps also discuss this issue with your Pivotal Opsmgr team.

With the version you original have - can you confirm that the raw bosh manifest (opsmgr does render it to your opsmgr disk somewhere, but I can't remember where right now) that the `{from: "credhub", deployment: "cf-xxxx"}` is correct?

AFAIK, bosh will complain that your local deployment doesn't have a link, even if you explicitly said "but I want the link to come from `deployment: xyz`. And you get the confusing error message you're seeing.

**Comment by AlbertoImpl** [comment]
Hi @drnic, the generated manifest seems correct to me:
```
instance_groups:
- name: deploy-service-broker
  azs:
  - first-az
  instances: 1
  lifecycle: errand
  jobs:
  - name: deploy-service-broker
    release: spring-cloud-broker
    consumes:
      credhub:
        from: credhub
        deployment: cf-ff909b6f51daaf435967
        optional: true
    provides: {}
```
And that was the confusing bit to me. I thought that consuming a link as optional would allow me to just say: try this, if not just ignore it because it's optional and I will use an `if_link` later.
