### ISSUE TITLE
BOSH agent does not respect manual swap-size override on GCP VMs

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/bosh#1840]
When provisioning a VM on GCP, BOSH does not respect the [`env.bosh.swap_size` directive on instance-groups](https://bosh.io/docs/manifest-v2.html#instance-groups) in the manifest. This override does work on AWS, though.

Sample minimal manifest to reproduce, using cloud-config references from bbl v4 against a BOSH director at v263.2.0:

```
instance_groups:
- name: swaptest
  azs:
  - z1
  env:
    bosh:
      swap_size: 512
  instances: 1
  jobs: []
  networks:
  - name: private
  stemcell: default
  vm_type: default
name: swaptest
releases: []
stemcells:
- alias: default
  os: ubuntu-trusty
  version: '3468.5'
update:
  canaries: 1
  canary_watch_time: 30000-1200000
  max_in_flight: 1
  serial: false
  update_watch_time: 5000-1200000
```

Relevant GCP VM type from the cloud config:

```
vm_types:
- cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: default
```

Results on GCP (from the Diego team's "warp-drive" environment) showing a 3.6G swap partition instead of a ~512M one:

```
bosh -e warp-drive -d swaptest ssh swaptest/0 lsblk | grep stdout

swaptest/5551403c-7be8-4f2a-8098-c6fa7796be5e: stdout | NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
swaptest/5551403c-7be8-4f2a-8098-c6fa7796be5e: stdout | sda      8:0    0    10G  0 disk
swaptest/5551403c-7be8-4f2a-8098-c6fa7796be5e: stdout | ├─sda1   8:1    0   2.9G  0 part /
swaptest/5551403c-7be8-4f2a-8098-c6fa7796be5e: stdout | ├─sda2   8:2    0   3.6G  0 part [SWAP]
swaptest/5551403c-7be8-4f2a-8098-c6fa7796be5e: stdout | └─sda3   8:3    0   3.6G  0 part /var/vcap/data
```

Results from same manifest deployed to AWS (the Diego team's "ketchup" environment) showing a swap partition with (roughly) the expected 512M size:

```
bosh -e ketchup -d swaptest ssh swaptest/0 lsblk | grep stdout
swaptest/8849664f-3bd6-4593-8a45-d877b1e6b36c: stdout | NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
swaptest/8849664f-3bd6-4593-8a45-d877b1e6b36c: stdout | xvda    202:0    0     3G  0 disk
swaptest/8849664f-3bd6-4593-8a45-d877b1e6b36c: stdout | └─xvda1 202:1    0     3G  0 part /
swaptest/8849664f-3bd6-4593-8a45-d877b1e6b36c: stdout | xvdb    202:16   0     4G  0 disk
swaptest/8849664f-3bd6-4593-8a45-d877b1e6b36c: stdout | ├─xvdb1 202:17   0 517.7M  0 part [SWAP]
swaptest/8849664f-3bd6-4593-8a45-d877b1e6b36c: stdout | └─xvdb2 202:18   0   3.5G  0 part /var/vcap/data
```

Happy to provide more context or assistance if needed!

Thanks,
Eric
