### ISSUE TITLE
Providing bosh link with only CA when certificate comes from credhub

### ISSUE THREAD

**Issue by akshaymankar** [cloudfoundry/bosh#1855]
I have a job in my release in which I want expose the credentials and the CA certificate. Usually the CA certificate comes from Credhub. My job spec looks like this:

```
properties:
    tls-cert:
       description: tls certificate, private_key and ca
provides:
- name: conn
   type: conn
   properties:
   - tls-cert.ca
```

When I try to deploy, I get this error:
```
Task 6 | 19:23:34 | Preparing deployment: Preparing deployment (00:00:00)
                   L Error: undefined method `has_key?' for "((tls-cert))":String
Task 6 | 19:23:34 | Error: undefined method `has_key?' for "((tls-cert))":String
```

Looking into debug logs shows me there is a problem at [this line](https://github.com/cloudfoundry/bosh/blob/v264.3.0/src/bosh-director/lib/bosh/director/deployment_plan/planner_factory.rb#L223)

I think the director is trying to resolve the links before it knows values of the variables.

As a workaround we had to split tls-cert into tls-cert.ca, tls-cert.private_key and tls-cert.certificate and the deployment manifest had to change accordingly. 

As a BOSH release author, it would be much more convenient if I didn't have to do that.
