### ISSUE TITLE
cloud-config Configure multiple az

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/bosh#1903]
Hi team:
   When i deploy cf-deployment ,i want using three azs, but i only hava two cluster and two network in vsphere, my property is:
```
---
azs:
- name: z1
  cloud_properties:
    datacenters:
    - name: DataCenter 
      clusters:
      - { Cluster2: {resource_pool: paas }}
- name: z2
  cloud_properties:
    datacenters:
    - name: DataCenter 
      clusters:
      - { Cluster1: {resource_pool: paas }}
- name: z3
  cloud_properties:
    datacenters:
    - name: DataCenter 
      clusters:
      - { Cluster1: {resource_pool: paas }}


networks:
- name: default
  subnets:
  - az: z1
    gateway: 192.168.7.254
    dns: [192.168.7.1]
    range: 192.168.7.0/24
    reserved: 
      - 192.168.7.1
      - 192.168.7.2
      - 192.168.7.3
      - 192.168.7.4
      - 192.168.7.5
      - 192.168.7.6
      - 192.168.7.7
      - 192.168.7.8
      - 192.168.7.9
      - 192.168.7.10
      - 192.168.7.254
      - 192.168.7.255
    cloud_properties:
      name: Net_1007
  - az: z2
    gateway: 192.168.6.254
    dns: [192.168.7.1]
    range: 192.168.6.0/25
    reserved: 
      - 192.168.6.1 - 192.168.6.20
      - 192.168.6.127
    cloud_properties:
      name: Net_1006
  - az: z3
    gateway: 192.168.6.254
    dns: [192.168.7.1]
    range: 192.168.6.128/25
    reserved: 
      - 192.168.6.254
      - 192.168.6.255
    cloud_properties:
      name: Net_1006
  

vm_types:
- name: minimal
  cloud_properties:
    cpu: 1
    ram: 4096
    disk: 10240
- name: small
  cloud_properties:
    cpu: 2
    ram: 8192
    disk: 10240
- name: small-highmem
  cloud_properties:
    cpu: 4
    ram: 32768
    disk: 10240

disk_types:
- disk_size: 5120
  name: 5GB
- disk_size: 10240
  name: 10GB
- disk_size: 100240
  name: 100GB

vm_extensions:
- name: load_balancer_for_mysql_proxy
- name: cf-router-network-properties
- name: cf-tcp-router-network-properties
- name: diego-ssh-proxy-network-properties
- name: 50GB_ephemeral_disk
  cloud_properties:
    disk: 51200
- name: 100GB_ephemeral_disk
  cloud_properties:
    disk: 102400

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: small-highmem
  network: default
```
But When deploy ,it throw ` Invalid gateway for network 'default': must be inside the range` error

**Comment by dpb587-pivotal** [comment]
Hi - line 46 is referring to a gateway of `192.168.6.254`, but a network of `192.168.6.0/25` only spans from `*.1` to `*.126`. I think you might want to double check those fields.

**Comment by geekyzk** [comment]
Hi @dpb587-pivotal
I want to divide a network(192.168.6.0/24 )into two az,if i config:
```
- az: z2
    gateway: 192.168.6.254
    dns: [192.168.7.1]
    range: 192.168.6.0/24
    reserved: 
      - 192.168.6.1 - 192.168.6.20
      - 192.168.6.151 - 192.168.6.255
    cloud_properties:
      name: Net_1006
  - az: z3
    gateway: 192.168.6.254
    dns: [192.168.7.1]
    range: 192.168.6.0/24
    reserved:
      - 192.168.6.1 - 192.168.6.150
      - 192.168.6.254
      - 192.168.6.255
    cloud_properties:
      name: Net_1006
```
it will throw` overring subnet`. So how divide a network segment to two az ?

**Comment by cppforlife** [comment]
@geekyzk you should just be able to specify following single subnet with
multiple azs:

```
- azs: [z2, z3]
  gateway: 192.168.6.254
  dns: [192.168.7.1]
  range: 192.168.6.0/24
  reserved:
     - 192.168.6.1 - 192.168.6.20
      - 192.168.6.254
      - 192.168.6.255
  cloud_properties:
    name: Net_1006
```

for your above approach, i dont believe we currently support finding subnet
based on a subnet of the range, but tbh i dont see a reason why that cant
change to be smarter.
