### ISSUE TITLE
bosh vms only display static ip address for vms configured with both dynamic and static networks

### ISSUE THREAD

**Issue by ywysuibian** [cloudfoundry/bosh#1908]
```
Version   263.3.0 (00000000)
CPI       openstack_cpi
```

I have some vms configured with both dynamic and static networks, but `bosh vms` only display static network ips for these vms.

I checked bosh director database, seems only static network ips stored in table `ip_addresses`.

**Comment by voelzmo** [comment]
Hey @ywysuibian 

It seems you're trying to use multiple networks on a single VM, which is only supported in a very specific case: http://bosh.io/docs/openstack-multiple-networks.html

Due to missing functionality in the bosh-agent, other cases involving dynamic networking or DHCP are not supported: https://github.com/cloudfoundry/bosh/issues/1129#issuecomment-186286247

**Comment by ywysuibian** [comment]
@voelzmo thank you for your kindly response.

I am not sure about `multiple networks`, maybe there is some misunderstanding in my previous description. 
I was using this kind of configuration for almost two years, and I just upgraded bosh director from a very lower version to 263.3, then upgraded cf from 253 to 270. During cf upgrading, all VMs were recreated (maybe due to stemcell upgrading),  and then `bosh vms` cannot display **private ip** of VMs which also configured with an **floating ip**.
 
My deployment yml looks like this
```yaml
instance_groups:
...
- instances: 1
  jobs:
  - name: aaaa
    release: aaaa-release
  - name: bbbb
    release: bbbb-release
  - name: cccc
    release: cccc-release
  name: xxxx
  networks:
  - default:
    - dns
    - gateway
    name: default
  - name: floating
    static_ips:
    - xxx.xxx.xxx.ipb
```

In the response from bosh_agent to director, I foud
```json
...
{
  "networks": {
    "default": {
      "cloud_properties": {

      },
      "default": [
        "dns",
        "gateway"
      ],
      "dns": [
        "xxx.xxx.xxx.xxx",
        "xxx.xxx.xxx.ipa"
      ],
      "gateway": "xxx.xxx.xxx.1",
      "ip": "xxx.xxx.xxx.ipa",
      "netmask": "255.255.255.0",
      "type": "dynamic"
    },
    "floating": {
      "cloud_properties": {
        
      },
      "ip": "xxx.xxx.xxx.ipb",
      "type": "vip"
    }
  }
...
}
```

But in bosh director database, I can only find one record in ip_addresses table related to this VM. After I delete this record, `bosh vms` became to display both ips.
