### ISSUE TITLE
Instance group with BOSH links is always redeployed even if there is no manifest change

### ISSUE THREAD

**Issue by bandesz** [cloudfoundry/bosh#1923]
Hi,

We have an instance group where a job consumes a BOSH link from an other job (on the same instance group). The instance group is always redeployed independent from the manifest change.
Even if we stop consuming the link the redeploy still happens.

We have the two jobs with the following config on the instance group:
```
- name: nats
  azs:
  - z1
  - z2
  instances: 2
  jobs:
  - name: nats
    release: nats
    provides:
      nats: {as: nats, shared: true}
  - name: datadog-nats
    release: datadog-for-cloudfoundry
    consumes:
      nats: {from: nats}
  [...]
```

In the spec file for nats we have this:

```
provides:
- name: nats
  type: nats
  properties:
  - nats.port
```

In the spec file for datadog-nats we have this:
```
[...]
consumes:
- name: nats
  type: nats
  optional: true

properties:
  nats.port:
    description: "Listening Port for NATS server."
    default: 4222
  [...]
```

We have the following template in the datadog-nats job which uses the optional nats link:
```
<%=
  nats_port = p('nats.port')
  respond_to?(:if_link) && if_link("nats") do |link|
    nats_port = link.p("nats.port")
  end
%>

init_config:

instances:
  - name: NATS server
    host: <%= spec.address %>
    port: <%= nats_port %>
    collect_response_time: true
[...]
```

BOSH deploy doesn't show any manifest change but redeploys only the two nats instances:

```
Task 3266

Task 3266 | 11:40:38 | Preparing deployment: Preparing deployment (00:00:14)
Task 3266 | 11:41:13 | Preparing package compilation: Finding packages to compile (00:00:01)
Task 3266 | 11:41:15 | Updating instance nats: nats/9eec3d9d-5d82-47c9-b5b2-115327d1a52a (0) (00:00:30)
Task 3266 | 11:41:45 | Updating instance nats: nats/832490c3-4f6f-4e8a-8909-22b373719536 (1) (00:00:29)
```

Running the `bosh events` command shows only this for the updated instances:
```
az: z1
changes:                                                                                  
  - configuration 
```

Is there something in the template file which might cause a redeploy?

## Environment

BOSH version: 264.7.0
BOSH cli version: 2.0.48
