### ISSUE TITLE
Changing blobstore from local to S3 bucket doesn't work

### ISSUE THREAD

**Issue by arthfl** [cloudfoundry/bosh#1939]
I had a blobstore in my local filesystem configured like this:

```
final-name: release-name
blobstore:
    provider: local
    options:
        blobstore_path: /tmp/release-name-blobs
```

at a later point i tried to change to blobstore to a S3 bucket:
```
final_name: release-name
blobstore:
    provider: s3
    options:
        bucket_name: release-name-blobs
```

but the following `bosh create-release` didn't upload anything, although it exited with "Succeeded".

I had to delete the `releases/` and `.final_builds/` directories to make bosh recreate the correct metadata for the blobstore.

There should **at least** be an error when putting files into the blobstore doesn't work. Also changing the blobstore should be supported, i'm probably not the only one who uses the local filesystem blobstore for early development stages and wants to change to something like S3 when going final.
