### ISSUE TITLE
Certificate variable type does not add SSL client certificate purpose

### ISSUE THREAD

**Issue by sbourlon** [cloudfoundry/bosh#1965]
Hi,

I think Bosh does not generate SSL client certificates correctly.

## Test 1:
When using the following certificate variable type:
```
    name: haproxy_client_ssl
    type: certificate
    options:
      ca: router_ca
      common_name: HAProxyClientSSL
      extended_key_usage:
      - server_auth
      - client_auth
```

The client certificate purposes does not have `SSL client: Yes`:
```
$ openssl x509 -in backend-crt.pem -text -noout -purpose
[...]
Certificate purposes:
SSL client : No
SSL client CA : No
SSL server : Yes
SSL server CA : No
Netscape SSL server : Yes
Netscape SSL server CA : No
S/MIME signing : No
S/MIME signing CA : No
S/MIME encryption : No
S/MIME encryption CA : No
CRL signing : No
CRL signing CA : No
Any Purpose : Yes
Any Purpose CA : Yes
OCSP helper : Yes
OCSP helper CA : No
Time Stamp signing : No
Time Stamp signing CA : No
```
## Test 2:
When using the following certificate variable type:
```
    name: haproxy_client_ssl
    type: certificate
    options:
      ca: router_ca
      common_name: HAProxyClientSSL
```

The client certificate purposes does not have `SSL client: Yes`:
```
$ openssl x509 -in backend-crt.pem -text -noout -purpose
[...]
Certificate purposes:
SSL client : No
SSL client CA : No
SSL server : Yes
SSL server CA : No
Netscape SSL server : Yes
Netscape SSL server CA : No
S/MIME signing : No
S/MIME signing CA : No
S/MIME encryption : No
S/MIME encryption CA : No
CRL signing : No
CRL signing CA : No
Any Purpose : Yes
Any Purpose CA : Yes
OCSP helper : Yes
OCSP helper CA : No
Time Stamp signing : No
Time Stamp signing CA : No
```
## Result:
The result of this misbehavior is the Gorouter in mTLS mode (Gorouter property `client_cert_validation: require`) does not accept the HAProxy client certificate by outputting the following error:
```
http: TLS handshake error from 10.244.0.150:43916: tls: failed to verify client's certificate: x509: certificate specifies an incompatible key usage
``` 

Thank you for your help!
