### ISSUE TITLE
Feature Request: I can list private S3 URIs under `releases` in my deployment manifest

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh#1969]
## Context

Our deployments have a mix of open source and closed source releases. We currently zip all these releases up with our deployment metadata and ship this to our users (PCF tiles). This zip file containing all the releases is now over 9GB which is a pain for users to upload and download. Although we would still provide this zip file for users who don't have internet access, a lighter distribution mechanism would be a big help.

## Proposed Solution

We can already specify the OSS URLs in our BOSH deployment manifest:

```
releases:
- name: concourse
  version: 3.3.2
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.3.2
  sha1: 2c876303dc6866afb845e728eab58abae8ff3be2
```

For the closed source releases, could we similarly specify URIs to private S3 buckets?

```
releases:
- name: some-private-release
  version: 1.2.3
  url: s3://my-bucket/some-private-release-1.2.3.tgz
  sha1: 2c876303dc6866afb845e728eab58abae8ff3be2
  access_key_id: ((release-access-key))
  secret_access_key: ((release-secret-key))
  region: us-east-1 # optional
  endpoint: https://s3.amazonaws.com # optional
```

If this seems like a reasonable change we'd be willing to make a PR.
