### ISSUE TITLE
Linking groups of properties does not export props with defaults to consuming specs

### ISSUE THREAD

**Issue by Gerg** [cloudfoundry/bosh#1976]
Given Job 1 with the following spec:

providing spec:
```yml
provides:
- name: my_database
  type: my_database
  properties:
  - db

properties:
  db.address:
    description: "The address of the database server"
  db.max_connections:
    default: 25
    description: "Maximum connections for the database"
```

and Job 2 with spec that consumes linked content:

consuming spec:
```yml
consumes:
- name: my_database
  type: my_database

properties: {}
```

when the template contains references to both non-defaulted and defaulted properties

template:
```
ADDRESS: <%= link("my_database").p("db.address") %>
MAX_CONNECTIONS: <%= link("my_database").p("db.max_connections") %>
```

the default properties from the provided job WILL NOT render if not provided in the deployment manifest

BOSH output:
```

Task 68 | 18:04:32 | Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'my-database-errand'. Errors are:
    - Unable to render templates for job 'my_database_errand'. Errors are:
      - Error filling in template 'template.yml.erb' (line 27: Can't find property '["db.max_connections"]')
```

UNLESS the properties with defaults are listed explicitly in the providing spec:

working job1 spec:
```
provides:
- name: my_database
  type: my_database
  properties:
  - db
  - db.max_connections          #  should I have to do that?
```
In this case, `db.max_connections` will successfully default to 25.

It is surprising that the default does not apply to these properties unless they are provided explicitly.
