### ISSUE TITLE
multiple NICs not showing up in a multi-homed virtualbox cpi deployment

### ISSUE THREAD

**Issue by gitstashpop** [cloudfoundry/bosh#1978]
I have a configuration for a multi-homed VM using a VirtualBox CPI, and although the NICs show up in `bosh instances`, when I `ssh` into the VM, I only see one NIC. I am not sure if this is an actual issue or just something silly I am doing. Any and all help would be appreciated. Thank you.

##### versions
stemcell: `bosh-warden-boshlite-ubuntu-trusty-go_agent  3586.23*`
bosh: `265.2.0`

##### Cloud config

```yml
networks:
- name: network1
  type: manual
  subnets:
  - range: 10.244.4.0/24
    gateway: 10.244.4.1
    dns:  ["8.8.8.8"]
    az: default
- name: network2
  type: manual
  subnets:
  - range: 10.244.5.0/24
    gateway: 10.244.5.1
    dns:  ["8.8.8.8"]
    az: default
```

##### Manifest

```yml
instance_groups:
 ...
  azs:
  - default
  stemcell: default
  networks:
  - name: network1
    default: [dns, gateway]
  - name: network2
```

##### instances output

Instance | Process State | AZ | IPs 
--- | --- | --- | ---
vmname/uuid | running | default | 10.244.4.4
|      |              |              | 10.244.5.2 |

##### `ip a` output

Once I `ssh`, I only see one NIC, even though the `bosh instances` output says the VM has two IP addresses:

```bash
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
336: we0crq5cpbmh-1@if337: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1
    link/ether ce:98:fd:51:b9:3e brd ff:ff:ff:ff:ff:ff
    inet 10.244.4.4/24 scope global we0crq5cpbmh-1
       valid_lft forever preferred_lft forever
```
##### director `ip` output

If I `ssh` into the director VM, I can see a lot of NICs without any IPs. Maybe this also has to do with the issue?

```bash
bosh/0:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.254.50.4/24 scope global lo:1
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:71:cd:85:96:e8 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.16/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:23:6d:2b:d1:54 brd ff:ff:ff:ff:ff:ff
    inet 192.168.50.6/24 brd 192.168.50.255 scope global eth1
       valid_lft forever preferred_lft forever
319: wbrdg-0af40400: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 5e:80:06:be:eb:31 brd ff:ff:ff:ff:ff:ff
    inet 10.244.4.1/24 scope global wbrdg-0af40400
       valid_lft forever preferred_lft forever
325: we0crq5cpbmb-0@if324: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master wbrdg-0af40400 state UP group default qlen 1
    link/ether da:a5:1e:01:2b:3a brd ff:ff:ff:ff:ff:ff
329: we0crq5cpbmd-0@if328: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master wbrdg-0af40400 state UP group default qlen 1
    link/ether 6a:90:4a:aa:67:c8 brd ff:ff:ff:ff:ff:ff
331: we0crq5cpbme-0@if330: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master wbrdg-0af40400 state UP group default qlen 1
    link/ether f6:4e:17:c4:2c:45 brd ff:ff:ff:ff:ff:ff
333: we0crq5cpbmf-0@if332: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master wbrdg-0af40400 state UP group default qlen 1
    link/ether b6:25:03:77:7f:8d brd ff:ff:ff:ff:ff:ff
335: we0crq5cpbmg-0@if334: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master wbrdg-0af40400 state UP group default qlen 1
    link/ether 8a:33:3b:f5:14:fd brd ff:ff:ff:ff:ff:ff
337: we0crq5cpbmh-0@if336: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master wbrdg-0af40400 state UP group default qlen 1
    link/ether 32:e0:a9:df:ca:de brd ff:ff:ff:ff:ff:ff
```
