### ISSUE TITLE
Providing a parent key link that doesn't carry value fails the deployment

### ISSUE THREAD

**Issue by Gerg** [cloudfoundry/bosh#1979]
Maybe related to #1976

Given Job 1 with the following spec:

providing spec:
```yml
provides:
- name: my_database
  type: my_database
  properties:
  - cc.database_encryption

properties:
  cc.database_encryption.keys:
    default: {}
    description: "label-key pairs for encrypting sensitive values in the CC database; labels must be < 256 characters long"
  cc.database_encryption.current_key_label:
    default: ""
    description: "current key label for encrypting values in the CC database"
```

and Job 2 with spec that consumes linked content:

consuming spec:
```yml
consumes:
- name: my_database
  type: my_database

properties: {}
```

when the template contains references to the exported property

template:
```
LABEL: <%= link("my_database").p("cc.database_encryption.current_key_label") %>
KEYS: <%= link("my_database").p("cc.database_encryption.keys") %>
```

When the manifest doesn't include the key `cc.database_encryption`

Then the deploy fails with the following error: 

```
Task 34430 | 20:53:34 | Preparing deployment: Preparing deployment (00:00:01)
                     L Error: Unable to process links for deployment. Errors are:
  - Link property cc.database_encryption in template cloud_controller_ng is not defined in release spec
```

If we instead change the spec for Job 1 to 

providing spec:
```yml
provides:
- name: my_database
  type: my_database
  properties:
  - cc.database_encryption.keys
  - cc.database_encryption.current_key_label

...
```

Then we are able to deploy, even when `cc.database_encryption` is not present in the deployment manifest.

We would expect to be able to provide parent keys in links, even if they are not included in the deployment manifest. It is inconvenient and unexpected to have to provide each child key in this case.

cc @jfmyers9 @mikexuu @GarfieldIsAPhilosopher
