### ISSUE TITLE
Feature request: allow to consume the same link from multiple instance groups.

### ISSUE THREAD

**Issue by s-matyukevich** [cloudfoundry/bosh#1994]
Consider the following scenario: I am using multi-cpi feature of bosh to deploy mysql cluster in 2 separate vsphere datacenters. In bosh I configured a separate CPI, AZ and network for each of the datacenters. (Note, that I must have 2 separate networks because my datacenters use 2 different CIDR ranges)  Because of the fact that I am using 2 different networks, I have to split the `myslq` instance group into 2 separate groups: `mysql_dc1` and `mysql_dc2`. There are some other instance groups that need to consume mysql link from both `mysql_dc1` and `mysql_dc2`. It would be nice If will be able to do this. Right now I have to rely on manual links, which is obviously a bad solution.

The manifest may look like the following.
```
- name: mysql_dc1
  jobs: 
  - name: mysql
    provides:
      mysql: {as: mysql_dc1}

- name: mysql_dc2
  jobs: 
  - name: mysql
    provides:
      mysql: {as: mysql_dc2}

- name: proxy
  jobs: 
  - name: proxy
    consumes:
      mysql: {from: ["mysql_dc1", "mysql_dc2"] }
```

**Comment by cppforlife** [comment]
> (Note, that I must have 2 separate networks because my datacenters use 2 different CIDR ranges) Because of the fact that I am using 2 different networks

you should be able to define network so that it covers multiple ranges spanning azs. for example:

```
networks:
- name: net1
  subnets:
  - range: 10.0.0.0/24
    azs: [z1]
    ...
  - range: 10.20.0.0/24
    ...
```
