### ISSUE TITLE
Still have to specify cpi property even if it's the default CPI for multi-CPI deployment

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#2028]
We are trying to leverage multiple-CPI to work around CPI backward compatibility issue. We set the old CPI (softlayer_legacy)  as the default one, and we expect to see there needs no change in cloud-config or manifest of existing deployments, but we found there must specify `cpi: xxxx` under azs section after deploying multiple-CPI, for example:

```
azs:
- cloud_properties:
    datacenter: lon02
  cpi: softlayer_legacy
  name: lon02
```

If there doesn't specify `cpi: softlayer_legacy`, we got the following error:

```
Task 180 | 08:42:04 | Creating missing vms: diego-cell/c49736ca-d2e3-4307-890e-d07db2cc4026 (1) (00:00:01)
                    L Error: CPI '' not found in cpi-config
```

We hope to see there still can use the default CPI if not specifying cpi property in cloud-config, is it possible? Thanks.

**Comment by jfmyers9** [comment]
Hi @mattcui,

You can use the `migrated_from:` block in the CPI config to acheive what you are looking for. Specifically you need to add:

```
migrated_from:
- name: ""
```

to the CPI that you wish to be associated with the original default CPI.

Let us know if that works for you.

Best,

@jfmyers9 && @GarfieldIsAPhilosopher, CF BOSH

**Comment by mattcui** [comment]
@jfmyers9 Thanks for your responses, but sorry that I didn't understand your solution to solve my problem with `migrated_from` in `cpi-config`, what kind of value should I set there? This is the first time to use multiple CPI, we didn't use the feature before. Below is our cpi-config:

```
cpis:
- name: softlayer_legacy
  type: softlayer_legacy
- name: softlayer
  type: softlayer
```

Thanks.
