### ISSUE TITLE
BOSH assumes uniqueness of IPs over all networks

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/bosh#2030]
**Describe the bug**
In our setup, we have some networks that are different IaaS networks (i.e. NSX networks) but reuse the same IP ranges and talk to the same director. 
The agents communicate to the director using SNAT, so connectivity from the agents to the BOSH director is possible.
Example: We have a cloud config with two networks `service-snat-1` and `service-snat-2`. Both networks are backed by a different IaaS network, i.e. `service-snat-1-ls` and `service-snat-2-ls`. However, they use the same IP range (i.e. 192.168.1.0/24). `service-snat-1` does not have to communicate with `service-snat-2`, only the agent in the service networks communicate to the BOSH director. This works fine, and we can live with the limitation that we can not talk from the director to the VMs, i.e. for `bosh ssh`. 

But: BOSH makes sure each IP is only used once in the whole installation. So when we deploy jobs to these networks, `service-snat-1` gets 192.168.1.2, while `service-snat-2` gets 192.168.1.3 etc.
We would like that BOSH allows reuse of IPs and only checks uniqueness in the context of a cloud config network.

**To Reproduce**
1. Deploy a bosh director on any IaaS
2. Upload stemcell and cloud config with these networks:
```
- name: service-snat-1
  subnets:
  - azs:
    - az1
    - az2
    - az3
    cloud_properties:
      name: service-snat-1-ls
    dns:
    - 172.16.1.5
    - 172.16.1.6
    gateway: 192.168.1.1
    range: 192.168.1.0/24
    reserved:
    - 192.168.1.1
    static: []
  type: manual
- name: service-snat-2
  subnets:
  - azs:
    - az1
    - az2
    - az3
    cloud_properties:
      name: service-snat-2-ls
    dns:
    - 172.16.1.5
    - 172.16.1.6
    gateway: 192.168.1.1
    range: 192.168.1.0/24
    reserved:
    - 192.168.1.1
    static: []
  type: manual
```
3. Deploy any release, once in network `service-snat-1` and once in `service-snat-2`

**Expected behavior**
As you will see, BOSH will successfully bring up the VMs in both networks. However, it will make sure that the used IPs are distinct (i.e. `service-snat-1` gets 192.168.1.2, `service-snat-2` gets 192.168.1.3), even though the networks are completely separated and each IP could be used twice.
Some background: we as a service provider allow our customers to define the IPs of their services themselves (since it will be VPN'd to their on-prem networks), so they could (and will) probably overlap.

**Code**
If I remove the uniqueness constraints on the IP address model (both in code and on the DB) and do the check of IPs in context of the network names, everything works as expected (BOSH assigns `192.168.1.2` to both `service-snat-1` and `service-snat-2`: 
https://github.com/cloudfoundry/bosh/compare/master...MatthiasWinzeler:overlapping-ips

I'm happy to create a proper PR with tests if this has the chance to be accepted.

**Versions (please complete the following information):**
 - Infrastructure: [e.g. AWS, GCP, etc] We tested with VSphere & NSX-T
 - BOSH version [e.g. 266.7] latest
 - BOSH CLI version [e.g. 5.1.1] latest
 - Stemcell version [e.g. ubuntu-xenial/97.10] latest
