### ISSUE TITLE
Bosh upload stemcell failed when used a custom stemcell

### ISSUE THREAD

**Issue by pulpham** [cloudfoundry/bosh#2031]
Hi,

I'm building CF on on VMware integrated Openstack environment.
Stemcell info:
- Ubuntu Trusty
- version: 3468.21
- OpenStack Full Stemcell

That stemcell contains qcow2 format image to create bosh director instance.
But because VMware doesn't support for that format type, so I converted it to vmdk format as below:
■Convert qcow2→vmdk 
`qemu-img convert -f qcow2 /vol01/stack/bosh-stemcell.qcow2  -O vmdk -o subformat=streamOptimized /vol01/stack/bosh-stemcell_v4.vmdk ; printf '\x03' | dd conv=notrunc of=/vol01/stack/bosh-stemcell_v4.vmdk bs=1 seek=$((0x4))`

■Then, create image:
`openstack image create --disk-format vmdk --public --file /vol01/stack/bosh-stemcell_v4.vmdk "bosh04"`

■Repack stemcell
`bosh repack-stemcell --version "3468.21" --empty-image --format openstack-light --cloud-properties "{\"image_id\":\"<target image_id>\"}" <src.tgz> <dst.tgz>`

■Upload to bosh director, but have error
`bosh upload stemcell <dst.tgz> --skip-if-exists`
Acting as client 'admin' on 'my-bosh'
Verifying stemcell... 
File exists and readable OK 
Verifying tarball... 
Read tarball OK 
Manifest exists FAILED
Stemcell is invalid, please fix, verify and upload again 

Anyone can help me to find the problem in my approach above which cause the error?

Thanks,

**Comment by voelzmo** [comment]
Hey @pulpham 

In your `repack-stemcell` command, is `src.tgz` the stemcell you donwloaded, or is it the stemcell you modified somehow above? As you're using `--empty-image` it should be safe to use the downloaded one, as all your previous modifications only apply to the image itself.

**Comment by pulpham** [comment]
Hi @voelzmo 
`src.tgz` the stemcell I donwloaded.
And `target image_id` is id of image I have created above.
Yes, all modifications only apply to that image itself.

**Comment by voelzmo** [comment]
Hey @pulpham 

could unpack your `dst.tgz` and paste the contents of `stemcell.MF`? After applying a similar set of commands, mine looks like this 
```
name: bosh-openstack-kvm-ubuntu-trusty-go_agent
version: 1.1.1
operating_system: ubuntu-trusty
sha1: 6ca278dacb71641d3b7ab5db6d340cf88dfbefeb
bosh_protocol: "1"
stemcell_formats:
- openstack-light
cloud_properties:
  architecture: x86_64
  auto_disk_config: true
  container_format: bare
  disk: 3072
  disk_format: qcow2
  hypervisor: kvm
  image_id: my-uuid-here
  infrastructure: openstack
  name: bosh-openstack-kvm-ubuntu-trusty-go_agent
  os_distro: ubuntu
  os_type: linux
  version: "3586.36"
```
