### ISSUE TITLE
Cannot upload stemcell for default CPI when cpi-config is in use

### ISSUE THREAD

**Issue by giner** [cloudfoundry/bosh#2065]
**Describe the bug**
Cannot upload stemcell for default CPI when cpi-config is in use

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy BOSH with default CPI targeting vSphere dc 1
2. Add a new CPI to cpi-config for vSphere dc 2 with alias vsphere-dc2
3. Add azs to cloud config so that some of them don't specify CPI and some of them specify CPI "vsphere-dc2"
4. Run `bosh upload stemcell URL`

**Expected behavior**
Stemcell should be uploaded to both default and vsphere-dc2 CPIs

**Versions (please complete the following information):**
 - Infrastructure: vSphere
 - BOSH version 268.1.0
 - BOSH CLI version 4.0.1
 - Stemcell version doesn't matter

**Deployment info:**
cpi-config:
```
cpis:
- name: vsphere-dc2
  properties:
    datacenters:
    - clusters:
      - cluster2_1
      - cluster2_2
      - cluster2_3
      datastore_pattern: ...
      disk_path: ...
      name: DC2
      persistent_datastore_pattern: ...
      template_folder: ...
      vm_folder: ...
    host: ...
    password: ...
    user: ...
  type: vsphere
```
AZs section from cloud config:
```
azs:
- cloud_properties:
    datacenters:
    - clusters:
      - cluster1_1: {}
      name: DC1
  name: z1
- cloud_properties:
    datacenters:
    - clusters:
      - cluster1_2: {}
      name: DC1
  name: z2
- cloud_properties:
    datacenters:
    - clusters:
      - cluster1_3: {}
      name: DC1
  name: z3
- cloud_properties:
    datacenters:
    - clusters:
      - cluster2_1: {}
      name: DC2
  cpi: vsphere-dc2
  name: p2z1
- cloud_properties:
    datacenters:
    - clusters:
      - cluster2_2: {}
      name: DC2
  cpi: vsphere-dc2
  name: p2z2
- cloud_properties:
    datacenters:
    - clusters:
      - cluster2_3: {}
      name: DC2
  cpi: vsphere-dc2
  name: p2z3
```
