### ISSUE TITLE
Redeploying without a job does not remove symlinks in `/var/vcap/packages/`

### ISSUE THREAD

**Issue by ndhanushkodi** [cloudfoundry/bosh#2070]
**Describe the bug**
BOSH redeploy after removing a job and release from an instance group does not remove symlinks from `/var/vcap/packages/package_name`

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director on bosh-lite
2. Upload a `xenial/97.18` stemcell and some bosh lite cloud config
3. Deploy 
```
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: bpm
    release: bpm
  name: foo
  networks:
  - name: default
  persistent_disk: 10000
  stemcell: default
  vm_type: default
name: foo
releases:
- name: bpm
  sha1: f2edbf3d1417a253205338c9941ca989cd2f8331
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.12.2
  version: 0.12.2
stemcells:
- alias: default
  os: ubuntu-xenial
  version: "97.18"
update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  serial: true
  update_watch_time: 10000-600000
variables: []
```
4. Deploy
```
instance_groups:
- azs:
  - z1
  instances: 1
  jobs: []
  name: foo
  networks:
  - name: default
  persistent_disk: 10000
  stemcell: default
  vm_type: default
name: foo
releases: []
stemcells:
- alias: default
  os: ubuntu-xenial
  version: "97.18"
update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  serial: true
  update_watch_time: 10000-600000
variables: []

```
4. `bosh ssh` to  instance,
5. Run `ll /var/vcap/packages/` on the vm to see that the symlink still appears, even though there is no monit job for it.
```
$ ll /var/vcap/packages/
total 0
drwxr-xr-x 2 root vcap  33 Oct 23 00:08 ./
drwxr-xr-x 1 root root 127 Oct 23 00:02 ../
lrwxrwxrwx 1 root root  73 Oct 22 23:58 bosh-dns -> /var/vcap/data/packages/bosh-dns/dfa1420b894d02a94f6c78d10b6ca2a64503c216/
lrwxrwxrwx 1 root root  68 Oct 22 23:58 bpm -> /var/vcap/data/packages/bpm/ad70b771095ae56de7d3f2bd09c0f8d5bdd2c126/

$ sudo su -
~# monit summary
The Monit daemon 5.2.5 uptime: 6m

Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
System 'system_localhost'           running
```

**Expected behavior**
The symlink should not exist, since we no longer list that job or release.

**Versions (please complete the following information):**
 - Infrastructure: lite
 - BOSH version:
```         
        {
            "id": "5062b790-0ea0-4ede-6c46-31045979a0fc",
            "name": "bosh",
            "version": "268.1.0"
        },
```
 - BOSH CLI version: `version 5.2.2-d737b7d3-2018-08-28T16:56:32Z`
 - Stemcell version `ubuntu-xenial/97.18`
 - ... other versions of releases being used: (BOSH DNS `1.10.0`, BPM `0.12.2`, and all other releases we've tried so far)
