### ISSUE TITLE
errand is listed twice in `bosh errands`

### ISSUE THREAD

**Issue by BeckerMax** [cloudfoundry/bosh#2095]
**Describe the bug**
If an errand uses a different name for the instance_group than for the job, it is listed twice in `bosh errands`

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy director on Virtualbox
2. Deploy zookeeper using following manifest

```
---
name: zookeeper

releases:
- name: zookeeper
  version: 0.0.9
  url: git+https://github.com/cppforlife/zookeeper-release

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: zookeeper
  azs: [z1, z2, z3]
  instances: 5
  jobs:
  - name: zookeeper
    release: zookeeper
    provides:
      conn: {shared: true}
    properties: {}
  - name: status
    release: zookeeper
    properties: {}
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default

- name: smoke-tests-ig
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: smoke-tests
    release: zookeeper
    properties: {}
  vm_type: default
  stemcell: default
  networks:
  - name: default
```

3. run `bosh errands`

**Expected behavior**
Errand is only listed once, either as `smoke-tests` or as `smoke-tests-ig`.

**Actual behavior**
Errand is listed once with its job name and once with its instance_group name:

```
$ bosh errands -d zookeeper
Using environment '192.168.50.6' as client 'admin'

Using deployment 'zookeeper'

Name
smoke-tests
smoke-tests-ig
status

3 errands

Succeeded
```

**Additional Info**
[This endpoint](https://github.com/cloudfoundry/bosh/blob/14700a77eed0d073e5dea450e44d07c7ce7b85ab/src/bosh-director/lib/bosh/director/api/controllers/deployments_controller.rb#L489) seems to collect both, instance_group names for standalone errands and jobs ran as errand for collocated errands.

**Versions (please complete the following information):**
 - Infrastructure: all
 - BOSH version 268.3.0
 - BOSH CLI version 5.4.0
 - Stemcell version bosh-warden-boshlite-ubuntu-trusty-go_agent?v=3586.57
