### ISSUE TITLE
How to generate fingerprint value for BOSH Release

### ISSUE THREAD

**Issue by prashantgnet** [cloudfoundry/bosh#2097]
**Describe the bug**
We have BOSH release tar.gz file with us and we would like to change code under it. As we don't have source code to create new BOSH release using BOSH command. we are modifying existing BOSH release .tar.gz file and re-creating it using tar command. we manually modify sha1 and version values under it. 
But we are not able about fingerprint value. Whether it will impact anything if we use the same fingerprint value or do we need to change it, if yes, then what is the process to change it.

**Comment by fatbearinc** [comment]
To make the question concrete, consider the following part of a **manifest.MF** file inside of a **release.tgz** file that contains an embedded **deploy.tgz** file:

```
jobs:
- fingerprint: 17b3eeebd5ecbb578705b6b083e930ff6ff66a9d
  name: deploy
  sha1: ecd4e3bfa8c1a07ed774645f6901a3e8b550d6ab
  version: 17b3eeebd5ecbb578705b6b083e930ff6ff66a9d
```

Suppose that I modify corresponding **deploy.tgz** and want to rebuild the BOSH release.

- I can use **sha1sum** to update the **sha1** field above. If not, what?
- How can I update the **fingerprint** field?
- How can I update the **version** field?

Thanks,
Steve
