### ISSUE TITLE
Records.json not present on VM

### ISSUE THREAD

**Issue by iainsproat** [cloudfoundry/bosh#2103]
**Describe the bug**
Bosh-DNS was unable to resolve an alias for another VM in the deployment.
On inspection, the Bosh-DNS logs showed that it was unable to open records file at `/var/vcap/instance/dns/records.json`.
The file was not present at this location.

**To Reproduce**
This was produced by the CFCR CI pipeline, the deployment manifest, cloud-config, stemcell, release version and logs of which can be [viewed here](https://ci.kubo.sh/teams/main/pipelines/kubo-deployment/jobs/deploy-old-k8s-multi-master-vsphere-lb/builds/188). We are not sure that this behaviour is consistently reproducible, the same configuration led to successful completion of the errand.

**Expected behavior**
We would expect a `records.json` to be present at `/var/vcap/instance/dns/records.json`.

**Logs**
bosh_dns.stdout.log
```
[File System] 2018/12/12 22:44:55 DEBUG - Stat '/var/vcap/instance/dns/records.json'
[RecordsRepo] 2018/12/12 22:44:55 ERROR - Unable to open records file at: /var/vcap/instance/dns/records.json
```

**Versions (please complete the following information):**
```
> bosh env
Name               khaleesi-bosh
UUID               38358db1-a58d-482f-a24b-1ca83e40b7a5
Version            268.4.0 (00000000)
Director Stemcell  ubuntu-xenial/170.9
CPI                vsphere_cpi
Features           compiled_package_cache: disabled
                   config_server: enabled
                   local_dns: enabled
                   power_dns: disabled
                   snapshots: disabled
User               admin
```
```
> bosh releases
Name       Version  Commit Hash
bosh-dns   1.10.0*  7c6515f
bpm        0.13.0*  91e202a
cfcr-etcd  1.8.0*   2b554df
docker     33.0.0*  db9736e
kubo       0.25.0*  7f3ac31
```

**Deployment info:**
[Manifest](https://github.com/cloudfoundry-incubator/kubo-deployment/blob/v0.25.0/manifests/cfcr.yml)
Runtime-config:
```
---	
addons:	
- include:	
    stemcell:	
    - os: ubuntu-trusty	
    - os: ubuntu-xenial	
  jobs:	
  - name: bosh-dns	
    properties:	
      api:	
        client:	
          tls: "((/dns_api_client_tls))"	
        server:	
          tls: "((/dns_api_server_tls))"	
      cache:	
        enabled: true	
      health:	
        client:	
          tls: "((/dns_healthcheck_client_tls))"	
        enabled: true	
        server:	
          tls: "((/dns_healthcheck_server_tls))"	
    release: bosh-dns	
  name: bosh-dns	
- include:	
    stemcell:	
    - os: windows2012R2	
    - os: windows2016	
    - os: windows1803	
    - os: windows1803	
  jobs:	
  - name: bosh-dns-windows	
    properties:	
      api:	
        client:	
          tls: "((/dns_api_client_tls))"	
        server:	
          tls: "((/dns_api_server_tls))"	
      cache:	
        enabled: true	
      health:	
        client:	
          tls: "((/dns_healthcheck_client_tls))"	
        enabled: true	
        server:	
          tls: "((/dns_healthcheck_server_tls))"	
    release: bosh-dns	
  name: bosh-dns-windows	
releases:	
- name: bosh-dns	
  sha1: d1aadbda5d60c44dec4a429cda872cf64f6d8d0b	
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.10.0	
  version: 1.10.0	
variables:	
- name: "/dns_healthcheck_tls_ca"	
  options:	
    common_name: dns-healthcheck-tls-ca	
    is_ca: true	
  type: certificate	
- name: "/dns_healthcheck_server_tls"	
  options:	
    ca: "/dns_healthcheck_tls_ca"	
    common_name: health.bosh-dns	
    extended_key_usage:	
    - server_auth	
  type: certificate	
- name: "/dns_healthcheck_client_tls"	
  options:	
    ca: "/dns_healthcheck_tls_ca"	
    common_name: health.bosh-dns	
    extended_key_usage:	
    - client_auth	
  type: certificate	
- name: "/dns_api_tls_ca"	
  options:	
    common_name: dns-api-tls-ca	
    is_ca: true	
  type: certificate	
- name: "/dns_api_server_tls"	
  options:	
    ca: "/dns_api_tls_ca"	
    common_name: api.bosh-dns	
    extended_key_usage:	
    - server_auth	
  type: certificate	
- name: "/dns_api_client_tls"	
  options:	
    ca: "/dns_api_tls_ca"	
    common_name: api.bosh-dns	
    extended_key_usage:	
    - client_auth	
  type: certificate	
```

**Additional context**
We were able to resolve this issue by recreating the VM.
