### ISSUE TITLE
Error message when deploying `redis-boshrelease` is unhelpful

### ISSUE THREAD

**Issue by klakin-pivotal** [cloudfoundry/bosh#2167]
**Describe the bug**
The error message that is produced when I attempt to deploy the currently latest version of `redis-boshrelease` (`927a7a3`) is unhelpful. It's not clear to me if my YML files are valid and this should have succeeded, or if I've done something wrong and we just need to enhance the error message. The behavior is the same on the two Bosh CLI versions mentioned in the **Versions** section below.

**To Reproduce**
* Bootstrap a Bosh Director on GCP using BBL, then use the "script" mentioned in the **Deployment info:** section with the version of `cloudfoundry/bosh-deployment` mentioned in the same section  to match our Director version.
* Extract the tarball that should be attached to this Issue.
* Reserve two Static IPs in your GCP project.
* Alter the `static_ips` list in `manifests/operators/creds.yml` to contain these IPs.
* Alter value of `network_name` in `manifests/operators/creds.yml` to be a network that's appropriate for your Bosh Director.
* Run the `bosh deploy` command mentioned in the **Logs** section.

**Expected behavior**
Either:
* A successful deployment
or
* An error message that contains enough information for me to correct my error

**Logs**
A `--debug` log from the Bosh deploy task is in this comment: https://github.com/cloudfoundry/bosh/issues/2167#issuecomment-477786551

The output from the bosh CLI follows:
```
bosh -e gcp -d redis deploy manifests/redis.yml -o manifests/operators/replace-network-and-instance-type.yml -l manifests/operators/creds.yml
Using environment '<GCP_IP_ADDRESS>' as client 'admin'

Using deployment 'redis'

Release 'bpm/1.0.3' already exists.

Release 'redis/15.2.4' for stemcell 'ubuntu-xenial/250.4' already exists.

+ stemcells:
+ - alias: default
+   os: ubuntu-trusty
+   version: '3541.12'

+ releases:
+ - name: bpm
+   sha1: f2bd126b17b3591160f501d88d79ccf0aba1ae54
+   url: git+https://github.com/cloudfoundry-incubator/bpm-release
+   version: 1.0.3
+ - name: redis
+   sha1: 7851118ef38a8393a70869b3b254e14ec4fd24a7
+   stemcell:
+     os: ubuntu-xenial
+     version: '250.4'
+   url: https://s3.amazonaws.com/redis-boshrelease/compiled-releases/redis/redis-15.2.4-ubuntu-xenial-250.4-20190130-060109-237608494-20190130060109.tgz
+   version: 15.2.4

+ update:
+   canaries: 0
+   canary_watch_time: 1000-20000
+   max_in_flight: 1
+   serial: true
+   update_watch_time: 1000-20000

+ addons:
+ - jobs:
+   - name: bpm
+     release: bpm
+   name: bpm

+ instance_groups:
+ - azs:
+   - z1
+   instances: 2
+   jobs:
+   - name: redis
+     properties:
+       password: "<redacted>"
+     release: redis
+   name: redis
+   networks:
+   - name: vip
+     static_ips:
+     - <GCP_IP_ONE>
+     - <GCP_IP_TWO>
+   persistent_disk: 10240
+   stemcell: default
+   vm_type: n1-standard-2
+ - azs:
+   - z1
+   instances: 1
+   jobs:
+   - name: sanity-tests
+     release: redis
+   lifecycle: errand
+   name: sanity-tests
+   networks:
+   - name: vip
+   stemcell: default
+   vm_type: n1-standard-2

+ name: redis

+ variables: []

Continue? [yN]: y

Task 39599

Task 39599 | 19:01:08 | Preparing deployment: Preparing deployment (00:00:00)
                     L Error: undefined method `shift' for nil:NilClass
Task 39599 | 19:01:08 | Error: undefined method `shift' for nil:NilClass

Task 39599 Started  Thu Mar 28 19:01:08 UTC 2019
Task 39599 Finished Thu Mar 28 19:01:08 UTC 2019
Task 39599 Duration 00:00:00
Task 39599 error

Updating deployment:
  Expected task '39599' to succeed but state is 'error'

Exit code 1
```

**Versions (please complete the following information):**
 - Infrastructure: GCP
 - BOSH version `268.6.0`
 - BOSH CLI version `5.4.0-891ff634-2018-11-14T00:21:14Z` and `5.0.1-2432e5e9-2018-07-18T21:41:03Z`
 - Stemcell version `bosh-google-kvm-ubuntu-xenial-go_agent-250.9`
 - BPM version: I think it's `0.12.3` on the director, `1.0.3` for this `redis` deployment.

**Deployment info:**
The script used to deploy our bosh director is:
```
bosh create-env ./bosh.yml --state ./bosh-state.json -o ./gcp/cpi.yml -o ./external-ip-not-recommended.yml -o ./jumpbox-user.yml -o ./hm/datadog.yml \
  --vars-store ./creds.yml \
  --var-file gcp_credentials_json=<(bosh int ./creds.yml --path /gcp_credentials_json)
```

The `bosh.yml` and ops files mentioned are sourced from the [bosh-deployment repo](https://github.com/cloudfoundry/bosh-deployment). The last commit used to deploy our directors was `9ffd8dd2452e48824a93235f846dc06f2177884b`.

FWIW: The `creds.yml` file doesn't contain much that's meaningful other than credentials.

I can provide our `bosh-state.json` (or any other information) if that would be helpful.

[redis-boshrelease.tar.gz](https://github.com/cloudfoundry/bosh/files/3019830/redis-boshrelease.tar.gz)

**Comment by klakin-pivotal** [comment]
FWIW, I get the same error with the following manifest:

```yaml
name: redis

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: redis
  azs: [z1]
  instances: 2
  vm_type: n1-standard-2
  stemcell: default
  persistent_disk: 10240
  networks: [{name: vip, static_ips: [10.0.0.1, 10.0.0.2]}]
  jobs:
  - name: redis
    release: redis
    properties:
      password: PASSWORD_REDACTED
- name: sanity-tests
  azs: [z1]
  instances: 1
  lifecycle: errand
  vm_type: n1-standard-2
  stemcell: default
  networks: [{name: vip}]
  jobs:
  - name: sanity-tests
    release: redis

variables:
- name: redis-password
  type: password

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-20000
  update_watch_time: 1000-20000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: bpm
  sha1: f2bd126b17b3591160f501d88d79ccf0aba1ae54
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
  version: 1.0.3
- name: redis
  sha1: 7851118ef38a8393a70869b3b254e14ec4fd24a7
  stemcell:
    os: ubuntu-xenial
    version: "250.4"
  url: https://s3.amazonaws.com/redis-boshrelease/compiled-releases/redis/redis-15.2.4-ubuntu-xenial-250.4-20190130-060109-237608494-20190130060109.tgz
  version: 15.2.4
```
