### ISSUE TITLE
Adding a stemcell exclusion rule causes other rules to be ignored

### ISSUE THREAD

**Issue by petewall** [cloudfoundry/bosh#2186]
**Describe the bug**
Using a stemcell exclusion rule will block some other rules from matching.

I have a deployment named "nginx", running ubuntu-xenial.  If I have this runtime config:
```yml
    exclude:
      deployments:
        - nginx
```

the addon will not be included.  However if I change the runtime config to:

```yml
    exclude:
      stemcell:
        - os: windows1803
        - os: windows2012R2
        - os: windows2016
        - os: windows2019
      deployments:
        - nginx
```

The add-on will be included.  This means that add-on will be excluded only if all values apply.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director on <IaaS> with <configuration options>
2. Upload <stemcell> and <cloud-config>
3. Deploy <manifest>
4. `bosh ssh` to a specific instance
5. Run <commands> on the vm to see the behavior

**Expected behavior**

**Logs**

```bash
ubuntu@vividlimegreen-ops-manager:~$ bosh deploy -d nginx nginx.yml
Using environment '10.0.0.5' as client 'ops_manager'

Using deployment 'nginx'

Release 'nginx/1.17.0' already exists.

  releases:
+ - name: os-conf
+   sha1: a60187f038d45e2886db9df82b72a9ab5fdcc49d
+   url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=20.0.0
+   version: 20.0.0

  addons:
+ - exclude:
+     deployments:
+     - nginx
+     stemcell:
+     - os: windows1803
+     - os: windows2012R2
+     - os: windows2016
+     - os: windows2019
+   jobs:
+   - name: login_banner
+     properties:
+       login_banner:
+         text: "<redacted>"
+     release: os-conf
+   name: simple-runtime-config

Continue? [yN]: n

Stopped

Exit code 1
ubuntu@vividlimegreen-ops-manager:~$
```

**Versions (please complete the following information):**
 - Infrastructure: GCP
 - BOSH version: 268.6.2
 - BOSH CLI version: 5.5.1-7850ac98-2019-05-21T22:28:36Z
 - Stemcell version: ubuntu-xenial/250.56

**Deployment info:**
Deployment manifest:

```yml
---
name: nginx

releases:
- name: "nginx"
  version: "1.17.0"
  url: "https://bosh.io/d/github.com/cloudfoundry-community/nginx-release?v=1.17.0"
  sha1: "13cf87b2394c7d3924f9d66836c56302fb46a90d"

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: nginx
  instances: 1
  azs: [ us-central1-b ]
  vm_type: medium
  stemcell: ubuntu
  networks:
  - name: vividlimegreen-services-subnet
  jobs:
  - name: nginx
    release: nginx
    properties:
      nginx_conf: ...
      pre_start: ...
update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
```

runtime config:

```yml
releases:
- name: "os-conf"
  version: "20.0.0"
  url: "https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=20.0.0"
  sha1: "a60187f038d45e2886db9df82b72a9ab5fdcc49d"

addons:
  - name: simple-runtime-config
    jobs:
    - name: login_banner
      release: os-conf
      properties:
        login_banner:
          text: Welcome to a the VM!
    exclude:
      stemcell:
        - os: windows1803
        - os: windows2012R2
        - os: windows2016
        - os: windows2019
      deployments:
        - nginx
```

**Additional context**

**Comment by petewall** [comment]
The [docs](https://bosh.io/docs/runtime-config/#placement-rules) say that they rules inside should be OR'd and include and exclude are AND'ed.  So:

If
    (include.stemcell OR include.deployment OR include.team ...) AND NOT 
    (exclude.stemcell OR exclude.deployment OR exclude.team ...)
Then the add-on should be included

Looking the code, the top level logic matches:
https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/director/addon/addon.rb#L42-L45

However, the logic inside the rules is way different:
https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/director/addon/filter.rb#L58-L97

The logic inside filter.rb seems to AND all of the internal rules.

**Comment by petewall** [comment]
So, this means that every rule added to the include section will mean the config will match fewer targets rather than more.  "If you have this stemcell AND this deployment name, then I'll be included"

Similarly, adding more fields to the exclusion list will mean it'll be excluded from fewer targets, rather than more.  "I will be excluded only if you have this stemcell AND you have this deployment name"

**Comment by mrosecrance** [comment]
I've dug into it a bit. The documentation is incorrect as you've pointed out. The AND functionality between directive rules (directive meaning exclude or include block) was put in explicitly so you can say "I want the add-on to apply to only the `zookeeper` job in `deployment-1` on the `xenial` stemcell but not if it's in `az1` and an `errand`". 

I've created a new story to update the documentation: https://www.pivotaltracker.com/story/show/166749915

I've also made a story to dig into the format that OR behavior might take: https://www.pivotaltracker.com/story/show/166751523

We're leery of changing existing behavior (this AND functionality has existed since 2016) and we've only had the incorrect documentation for a few months.

**Comment by mrosecrance** [comment]
It is possible to get some `OR` behavior by specifying two of the same add-ons with different names. 
```
addons:
- name: dummy
  jobs:
  - name: dummy
    release: dummy
  include:
    deployments: [dep1]
- name: dummy2
  jobs:
  - name: dummy
    release: dummy
  include:
    deployments: [dep2]
  exclude:
     stemcell:
        - os: windows1803
```
