### ISSUE TITLE
Create deployment does not respect CLI flags --max-in-flight and --canary

### ISSUE THREAD

**Issue by FlorianNachtigall** [cloudfoundry/bosh#2193]
**Describe the bug**

Deploying with CLI options `--max-in-flight` and `--canaries` does not take any effect. Neither the global nor the instance_group level update section of the manifest is overridden.

The `deployments_controller.rb` does not propagate the properties for the `POST /deployments` endpoint used for `bosh deploy`. In contrast the `PUT /deployments/:deployment/jobs/:job` endpoint used for `bosh  start/restart/stop/recreate` propagates correctly.

**To Reproduce**

```bash
$ bosh deploy -d dummy --canaries=0 --max-in-flight=1 dummy.yml
Task 37 | 22:19:39 | Preparing deployment: Preparing deployment (00:00:04)
Task 37 | 22:19:43 | Preparing deployment: Rendering templates (00:00:01)
Task 37 | 22:19:44 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 37 | 22:19:44 | Creating missing vms: dummy/ddb07731-5d7a-488d-87c9-ced196549ef6 (0)
Task 37 | 22:19:44 | Creating missing vms: dummy/738690eb-c393-4356-bee4-360e2610450e (3)
Task 37 | 22:19:44 | Creating missing vms: dummy/3a23d3fa-f9a3-4ee0-8eb3-d349af2cd716 (1)
Task 37 | 22:19:44 | Creating missing vms: dummy/8945375e-24b6-4290-8b90-3e8c23be510e (2) (00:00:15)
Task 37 | 22:20:02 | Creating missing vms: dummy/738690eb-c393-4356-bee4-360e2610450e (3) (00:00:18)
Task 37 | 22:20:02 | Creating missing vms: dummy/3a23d3fa-f9a3-4ee0-8eb3-d349af2cd716 (1) (00:00:18)
Task 37 | 22:20:02 | Creating missing vms: dummy/ddb07731-5d7a-488d-87c9-ced196549ef6 (0) (00:00:18)
Task 37 | 22:20:02 | Updating instance dummy: dummy/ddb07731-5d7a-488d-87c9-ced196549ef6 (0) (canary)
Task 37 | 22:20:02 | Updating instance dummy: dummy/3a23d3fa-f9a3-4ee0-8eb3-d349af2cd716 (1) (canary) (00:00:15)
Task 37 | 22:20:18 | Updating instance dummy: dummy/ddb07731-5d7a-488d-87c9-ced196549ef6 (0) (canary) (00:00:16)
Task 37 | 22:20:18 | Updating instance dummy: dummy/738690eb-c393-4356-bee4-360e2610450e (3)
Task 37 | 22:20:18 | Updating instance dummy: dummy/8945375e-24b6-4290-8b90-3e8c23be510e (2)
Task 37 | 22:20:33 | Updating instance dummy: dummy/738690eb-c393-4356-bee4-360e2610450e (3) (00:00:15)
Task 37 | 22:20:34 | Updating instance dummy: dummy/8945375e-24b6-4290-8b90-3e8c23be510e (2) (00:00:16)

Task 37 Started  Thu Jun 20 22:19:39 UTC 2019
Task 37 Finished Thu Jun 20 22:20:34 UTC 2019
Task 37 Duration 00:00:55
Task 37 done

Succeeded
```

During deployment a `canary` instance has been created and according to the timestamps, `max_in_flight` is 3 as opposed to the cli specified parameter.

**Expected behaviour**

Respect both properties during create deployment.

**Versions (please complete the following information):**
 - Infrastructure: Virtualbox
 - BOSH version `110a0453d`
 - BOSH CLI version v5.5.1
 - Stemcell version [ubuntu-xenial/250.9]

**Deployment info:**

```yaml
---
# BOSH Director must have Cloud Config with the following properties:
# - vm_type: tiny
# - network: manual

name: dummy

releases:
- name: dummy
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: dummy
  instances: 4
  azs: [z1]
  update:
    max_in_flight: 3
    canaries: 2
  vm_type: default
  stemcell: ubuntu
  networks:
  - name: default
  jobs:
  - name: dummy
    release: dummy

update:
  canaries: 1
  max_in_flight: 6
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
```

**Additional context**
https://www.pivotaltracker.com/n/projects/956238/stories/126020395
https://www.pivotaltracker.com/n/projects/956238/stories/139515855

/cc @friegger @s4heid
