### ISSUE TITLE
Certificate Issue when uploading Release in vSphere

### ISSUE THREAD

**Issue by keithkroeger** [cloudfoundry/bosh#2211]
When we upload a release to a newly-deployed vSphere director, we see the following:
```
bash-5.0# bosh upload-release syslog.tgz
Using environment 'xxx.xxx.xxx.xxx' as client 'admin'

######################################################### 100.00% 144.73 MB/s 0s
Task 39

Task 39 | 14:49:28 | Extracting release: Extracting release (00:00:01)
Task 39 | 14:49:29 | Verifying manifest: Verifying manifest (00:00:00)
Task 39 | 14:49:29 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 39 | 14:49:29 | Creating new packages: blackbox/315061d6e1128b4bd8825f23204cc7e36a966f0d (00:00:00)
                   L Error: Failed to upload blob, code 1, output: 'Error running app - Putting dav blob b0356db7-4672-4c6a-9d93-603d37717e4e: Put https://xxx.xxx.xxx.xxx:25250/7e/b0356db7-4672-4c6a-9d93-603d37717e4e: x509: cannot validate certificate for 10.139.44.11 because it doesn't contain any IP SANs', error: ''
Task 39 | 14:49:29 | Error: Failed to upload blob, code 1, output: 'Error running app - Putting dav blob b0356db7-4672-4c6a-9d93-603d37717e4e: Put https://xxx.xxx.xxx.xxx:25250/7e/b0356db7-4672-4c6a-9d93-603d37717e4e: x509: cannot validate certificate for 10.139.44.11 because it doesn't contain any IP SANs', error: ''

Task 39 Started  Fri Sep 27 14:49:28 UTC 2019
Task 39 Finished Fri Sep 27 14:49:29 UTC 2019
Task 39 Duration 00:00:01
Task 39 error

Uploading release file:
  Expected task '39' to succeed but state is 'error'

Exit code 1

```

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director on vSphere
2. Attempt to upload release

We saw https://github.com/cloudfoundry/bosh/issues/1813, and also attempted to completely clear out our credentials and have them regenerated, to no avail.

We also verified that the cert generated included our IP address, for example:
```
bosh int creds.yml --path=/mbus_bootstrap_ssl/certificate > test.crt
openssl x509 -noout -text -in test.crt
```

**Expected behavior**
In Openstack, this works as desired.

**Versions (please complete the following information):**
 - Infrastructure: vSphere
 - BOSH version bosh-268.2.1-ubuntu-xenial-170.9
    bpm-0.12.3-ubuntu-xenial-97.17-20180919-183904-508666998-20180919183910
    bosh-vsphere-cpi-release-50
 - BOSH CLI version version 3.0.1-712bfd7-2018-03-13T23:26:43Z
 - Stemcell version bosh-stemcell-97.12-vsphere-esxi-ubuntu-xenial-go_agent

**Deployment info:**
Our manifest generates creds using these definitions:
```
- name: admin_password
  type: password
- name: blobstore_director_password
  type: password
- name: blobstore_agent_password
  type: password
- name: hm_password
  type: password
- name: mbus_bootstrap_password
  type: password
- name: nats_password
  type: password
- name: postgres_password
  type: password
- name: default_ca
  options:
    common_name: ca
    is_ca: true
  type: certificate
- name: mbus_bootstrap_ssl
  options:
    alternative_names:
    - ((internal_ip))
    ca: default_ca
    common_name: ((internal_ip))
  type: certificate
- name: director_ssl
  options:
    alternative_names:
    - ((internal_ip))
    ca: default_ca
    common_name: ((internal_ip))
  type: certificate
- name: nats_ca
  options:
    common_name: default.nats-ca.bosh-internal
    is_ca: true
  type: certificate
- name: nats_server_tls
  options:
    alternative_names:
    - ((internal_ip))
    ca: nats_ca
    common_name: default.nats.bosh-internal
    extended_key_usage:
    - server_auth
  type: certificate
- name: nats_clients_director_tls
  options:
    ca: nats_ca
    common_name: default.director.bosh-internal
    extended_key_usage:
    - client_auth
  type: certificate
- name: nats_clients_health_monitor_tls
  options:
    ca: nats_ca
    common_name: default.hm.bosh-internal
    extended_key_usage:
    - client_auth
  type: certificate
- name: blobstore_ca
  options:
    common_name: default.blobstore-ca.bosh-internal
    is_ca: true
  type: certificate
- name: blobstore_server_tls
  options:
    ca: blobstore_ca
    common_name: ((internal_ip))
  type: certificate
```
**Additional context**
To solve this, we added the following to every certificate definition:
```
    alternative_names:
    - ((internal_ip))
```
