### ISSUE TITLE
Remove Potential error source of Nats CA rotation documentation

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry/bosh#2230]
**Is your feature request related to a problem? Please describe.**
https://bosh.io/docs/nats-ca-rotation/#step-3-update-the-director-health-monitor-and-nats-server-jobs-to-remove-references-for-the-old-nats-ca-and-certificates-signed-by-it

In this guide you explain how to rotate Nats CA certificates. In step one you add the new CA certificates and in step 2 you set everything to use the new CA. The issue is if you forget to remove this ops file after running the step renaming and removing the new certs to the name of the old CA certificate, you will get a new set of certificates and all agents will be unresponsive. In the same fashion, you can use the Step 3 Ops file in the first step, resulting in unresponsive agents as bosh expects the new certs. Those issues can be avoided by removing the variables block from the second ops file. If you ran it with ops file 1 first, the vars are already present. If you ran the ops file that replaces the old Certificate with the new ones, the script will error, as it will do if you use the second ops file on the first run. This makes sure you do not do the Rotation in the wrong order. 

**Describe the solution you'd like**
Change the second ops file to: 

```yaml
---
- type: replace
  path: /instance_groups/name=bosh/properties/nats/tls/ca?
  value: ((nats_server_tls_2.ca))

- type: replace
  path: /instance_groups/name=bosh/properties/nats/tls/server?
  value:
    certificate: ((nats_server_tls_2.certificate))
    private_key: ((nats_server_tls_2.private_key))

- type: replace
  path: /instance_groups/name=bosh/properties/nats/tls/client_ca?
  value:
    certificate: ((nats_ca_2.certificate))
    private_key: ((nats_ca_2.private_key))

- type: replace
  path: /instance_groups/name=bosh/properties/nats/tls/director?
  value:
    certificate: ((nats_clients_director_tls_2.certificate))
    private_key: ((nats_clients_director_tls_2.private_key))

- type: replace
  path: /instance_groups/name=bosh/properties/nats/tls/health_monitor?
  value:
    certificate: ((nats_clients_health_monitor_tls_2.certificate))
    private_key: ((nats_clients_health_monitor_tls_2.private_key))
```
(aka remove all the variables addition)
This will make sure that you get an error if you try to run the ops files out of order by accident, also the variables should already be there at this point.
**Describe alternatives you've considered**
Changing the documentation so first you move the old certificate to _old and change all scripts so no variable block is needed at any point and the ops for the first step uses _old for most things and later ops files get shorter.
