### ISSUE TITLE
link aliases return duplicate IPs if defined in multiple instance groups

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [cloudfoundry/bosh#2241]
**To Reproduce**
Given:
- a job that provides a link
- a manifest that places that job in two instance groups
- in each instance group define a unique alias (e.g. `mylink.internal` and `yourlink.internal`)
- in each instance group define a common alias (e.g. `ourlink.internal`)

ssh into a VM
`dig mylink.internal`
`dig ourlink.internal`

**Expected behavior**
- `dig ourlink.internal` returns the IPs of each VM in either instance group once
- all 3 aliases return the same set of IPs (as links are scoped to a job in a deployment and not an instance group)

**Actual behavior**
`dig ourlink.internal` returns the IPs of each VM in either instance group four times

**Logs**
```
dig mylink.internal

;; ANSWER SECTION:
mylink.internal.	0	IN	A	10.244.0.9
mylink.internal.	0	IN	A	10.244.0.11
mylink.internal.	0	IN	A	10.244.0.10
mylink.internal.	0	IN	A	10.244.0.8
```
```
dig ourlink.internal

;; ANSWER SECTION:
ourlink.internal.	0	IN	A	10.244.0.10
ourlink.internal.	0	IN	A	10.244.0.8
ourlink.internal.	0	IN	A	10.244.0.10
ourlink.internal.	0	IN	A	10.244.0.11
ourlink.internal.	0	IN	A	10.244.0.11
ourlink.internal.	0	IN	A	10.244.0.10
ourlink.internal.	0	IN	A	10.244.0.9
ourlink.internal.	0	IN	A	10.244.0.11
ourlink.internal.	0	IN	A	10.244.0.9
ourlink.internal.	0	IN	A	10.244.0.9
ourlink.internal.	0	IN	A	10.244.0.8
ourlink.internal.	0	IN	A	10.244.0.10
ourlink.internal.	0	IN	A	10.244.0.11
ourlink.internal.	0	IN	A	10.244.0.9
ourlink.internal.	0	IN	A	10.244.0.8
ourlink.internal.	0	IN	A	10.244.0.8
```

**Versions (please complete the following information):**
 - Infrastructure: boshlite
 - BOSH version 270.11.0
 - BOSH CLI version 6.2.1
 - Stemcell version ubuntu-xenial/621.55
 - bosh-dns 1.18

**Deployment info:**
```
name: nothing

releases:
- name: nonsense
  version: latest

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 0
  max_in_flight: 20
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: nothing
  azs: [z1]
  instances: 2
  jobs:
  - name: nothing
    release: nonsense
    provides:
      nothing:
        shared: true
        aliases:
        - domain: "mylink.internal"
        - domain: "ourlink.internal"
  vm_type: default
  stemcell: default
  networks:
  - name: default
    default:
    - dns
    - gateway
- name: nothing2
  azs: [z1]
  instances: 2
  jobs:
  - name: nothing
    release: nonsense
    provides:
      nothing:
        shared: true
        aliases:
        - domain: "yourlink.internal"
        - domain: "ourlink.internal"
  vm_type: default
  stemcell: default
  networks:
  - name: default
    default:
    - dns
    - gateway
```
