### ISSUE TITLE
Add a date/timestamp into stemcell.MF files

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#336]
Current stemcell.MF contain a sha1 which is great. Could a timestamp be also added for when the stemcell was created?

Current stemcell.MF looks like this:

``` yaml

---
name: micro-bosh-stemcell
version: '776'
bosh_protocol: 1
sha1: b01864902ca3608411c2c7e791176a8a33567810
cloud_properties:
  name: micro-bosh-stemcell
  version: '776'
  infrastructure: aws
  architecture: x86_64
  root_device_name: /dev/sda1
  ami:
    us-east-1: ami-427b092b
```
