### ISSUE TITLE
Create dedicated user/pass for health manager

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#338]
By default the HM assumes admin:admin is available to communicate with director; but this is deleted when the first user is created.

The aws bootstrap (sadly) worked around this bug by scripting the creation of a new "hm" user and passing those credentials into the micro_bosh.yml. https://github.com/cloudfoundry/bosh/blob/master/bosh_cli_plugin_aws/templates/micro_bosh.yml.erb#L55-L59 - 

Perhaps automatically create the hm user (or delete & recreate if password changes) if it is specified in the properties; or the micro_bosh.yml `apply_spec.properties`:

``` yaml
apply_spec:
  properties:
    hm:
      director_account:
        user: hm
        password: TOKEN
```
