### ISSUE TITLE
bosh diff - "Could not find networks." - when they were fully defined in the template

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#344]
It should be possible for a bosh diff template to fully define the networks for a deployment. Currently, if your initial deployment file does not contain `networks:` key the `bosh diff` command will fail with "Could not find networks.".

It shouldn't complain if the target template contains `networks:`.

The current workaround is to include an empty networks definition:

``` yaml

---
name: redis
director_uuid: 4ae3a0f0-70a5-4c0d-95f2-7fafaefe8b9e
networks: {}
```
