### ISSUE TITLE
Unable to use properties in manifest

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry/bosh#377]
When running `bosh deploy` with the following manifest (showing problematic part):

``` yaml
  - name: sslproxy
    release: sslproxy
    template:
      - sslproxy
    instances: 2
    resource_pool: infrastructure
    networks:
      - name: default
        default: [dns, gateway]
      - name: floating
        static_ips:
          - 192.0.2.1
          - 192.0.2.2
    properties:
      sslproxy:
        https:
          ssl_key: |
            <%= property("ssl_key") %>
          ssl_cert: |
            <%= property("ssl_crt") %>
```

I get the following error: `undefined method 'property' for main:Object (NoMethodError)`

```
from /.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/erb.rb:838:in `eval'
from /.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/erb.rb:838:in `result'
from /ruby-1.9.3-p194@bosh/gems/bosh_cli-1.5.0.pre.859/lib/cli/core_ext.rb:72:in `load_yaml_file'
from /ruby-1.9.3-p194@bosh/gems/bosh_cli-1.5.0.pre.859/lib/cli/deployment_helper.rb:15:in `prepare_deployment_manifest'
from /ruby-1.9.3-p194@bosh/gems/bosh_cli-1.5.0.pre.859/lib/cli/commands/deployment.rb:89:in `perform'
from /ruby-1.9.3-p194@bosh/gems/bosh_cli-1.5.0.pre.859/lib/cli/command_handler.rb:57:in `run'
from /ruby-1.9.3-p194@bosh/gems/bosh_cli-1.5.0.pre.859/lib/cli/runner.rb:59:in `run'
from /ruby-1.9.3-p194@bosh/gems/bosh_cli-1.5.0.pre.859/lib/cli/runner.rb:18:in `run'
from /ruby-1.9.3-p194@bosh/gems/bosh_cli-1.5.0.pre.859/bin/bosh:7:in `<top (required)>'
from /ruby-1.9.3-p194@bosh/bin/bosh:19:in `load'
from /ruby-1.9.3-p194@bosh/bin/bosh:19:in `<main>'
from /ruby-1.9.3-p194@bosh/bin/ruby_noexec_wrapper:14:in `eval'
from /ruby-1.9.3-p194@bosh/bin/ruby_noexec_wrapper:14:in `<main>'
```

I'm using `BOSH 1.5.0.pre.859`
