### ISSUE TITLE
vcloud cpi control properties (e.g. wait_max ) are ignored in bosh-release

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/bosh#548]
The vcloud cpi accepts some control properties such as configuration of the max time for a single task, through a set of control properties see https://github.com/vchs/bosh_vcloud_cpi/blob/master/spec/integration/test_settings_sample.yml#L14

```
vcds:
  - url: https://vcd-wdc
    user: cpi
    password: password
    entities:
      organization: tempest-1
      virtual_datacenter: tempest-1-org-vdc
      vapp_catalog: cpi-dev
      media_catalog: cpi-dev
      media_storage_profile: "*"
      vm_metadata_key: agent-env
      control:
        wait_max: 400 # maximum wait seconds for a single task
        wait_delay: 10 # delay in seconds for pooling next task status
        cookie_timeout: 1200 # timeout in seconds after which session must be re-created
        retry_max: 5 # maximum attempts
        retry_delay: 500 # delay of first retry, the next is * 2
```

while this works fine with a micro-bosh instance, this is ignored for a bosh release, likely because the control hash is not passed to the bosh_director:

https://github.com/cloudfoundry/bosh/blob/920ac9c92224868106ee32ed76a85f1d5d37d3c5/release/jobs/director/templates/director.yml.erb.erb#L287

The workaround I applied to configure retries is to manually patch the default value on the bosh-api vm

```
root@f4ad0c63-ed40-4933-88fb-b4a3d49ef9de:~# vi /var/vcap/packages/director/gem_home/gems/bosh_vcloud_cpi-0.5.2/lib/cloud/vcloud/vcd_client.rb
   WAIT_MAX       = 6000    # maximum wait seconds for a single task
root@f4ad0c63-ed40-4933-88fb-b4a3d49ef9de:~# monit restart director worker_1 worker_2 worker_3
```
