### ISSUE TITLE
Failure to deploy microbosh to openstack with v2707

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry/bosh#645]
Trying to deploy CF with BOSH 2707 and got the following error.

```
ubuntu@bosh:~/bosh-workspace/deployments$ bosh micro deployment micro_bosh/
/var/lib/gems/1.9.1/gems/bosh_cli_plugin_micro-    1.2707.0/lib/bosh/deployer/instance_manager/openstack.rb:114:in `discover_client_services_ip':    undefined method `floating_ip_address' for nil:NilClass (NoMethodError)
    from /var/lib/gems/1.9.1/gems/bosh_cli_plugin_micro-  1.2707.0/lib/bosh/deployer/instance_manager/openstack.rb:63:in `client_services_ip'
    from /var/lib/gems/1.9.1/gems/bosh_cli_plugin_micro-1.2707.0/lib/bosh/cli/commands/micro.rb:55:in `set_current'
    from /var/lib/gems/1.9.1/gems/bosh_cli_plugin_micro-1.2707.0/lib/bosh/cli/commands/micro.rb:32:in `micro_deployment'
    from /var/lib/gems/1.9.1/gems/bosh_cli-1.2707.0/lib/cli/command_handler.rb:57:in `run'
    from /var/lib/gems/1.9.1/gems/bosh_cli-1.2707.0/lib/cli/runner.rb:56:in `run'
    from /var/lib/gems/1.9.1/gems/bosh_cli-1.2707.0/lib/cli/runner.rb:16:in `run'
    from /var/lib/gems/1.9.1/gems/bosh_cli-1.2707.0/bin/bosh:7:in `<top (required)>'
    from /usr/local/bin/bosh:23:in `load'
    from /usr/local/bin/bosh:23:in `<main>'
```

The manifest used is 

```

---
name: microbosh-openstack

logging:
  level: DEBUG

network:
  type: manual
  ip: 172.16.2.39
  cloud_properties:
    net_id: fa9e0c74-059f-4389-8bc4-fd98a15eefd4

resources:
  persistent_disk: 32768
  cloud_properties:
    instance_type: m1.medium

cloud:
  plugin: openstack
  properties:
    openstack:
      auth_url: *****
      username: *****
      api_key: *****
      tenant: *****
      default_security_groups: ["ssh", "bosh"]
      default_key_name: microbosh
      private_key: /home/ubuntu/.ssh/microbosh
      boot_from_volume: true

apply_spec:
  properties:
    director:
      max_threads: 3
    hm:
      resurrector_enabled: true
    ntp:
      - 0.north-america.pool.ntp.org
      - 1.north-america.pool.ntp.org
```
