### ISSUE TITLE
'log writing failed' message while deploying microBOSH to AWS

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/bosh#702]
I deploy microBOSH to AWS using `light-bosh-stemcell-2776-aws-xen-hvm-ubuntu-trusty-go_agent stemcell`. `bosh micro deploy` command writes error message while writing logs at the end.

Here is stdout output and supplementary information about deployment.

---

```
$ bosh micro deploy light-bosh-stemcell-2776-aws-xen-hvm-ubuntu-trusty-go_agent.tgz

No `bosh-deployments.yml` file found in current directory.

Conventionally, `bosh-deployments.yml` should be saved in /Users/lexsys/code.
Is /Users/lexsys/code/mkbosh a directory where you can save state? (type 'yes' to continue): yes
Deploying new micro BOSH instance `manifest.yml' to `Unknown Director' (type 'yes' to continue): yes

Verifying stemcell...
File exists and readable                                     OK
Verifying tarball...
Read tarball                                                 OK
Manifest exists                                              OK
Stemcell image file                                          OK
Stemcell properties                                          OK

Stemcell info
-------------
Name:    bosh-aws-xen-hvm-ubuntu-trusty-go_agent
Version: 2776

  Started deploy micro bosh
  Started deploy micro bosh > Unpacking stemcell. Done (00:00:00)
  Started deploy micro bosh > Uploading stemcell. Done (00:00:06)
  Started deploy micro bosh > Creating VM from ami-96d141fe light. Done (00:00:41)
  Started deploy micro bosh > Waiting for the agent. Done (00:01:47)
  Started deploy micro bosh > Updating persistent disk
  Started deploy micro bosh > Create disk. Done (00:00:04)
  Started deploy micro bosh > Mount disk. Done (00:00:10)
     Done deploy micro bosh > Updating persistent disk (00:00:23)
  Started deploy micro bosh > Stopping agent services. Done (00:00:04)
  Started deploy micro bosh > Applying micro BOSH spec. Done (00:00:40)
  Started deploy micro bosh > Starting agent services. Done (00:00:02)
  Started deploy micro bosh > Waiting for the director. Done (00:00:05)
     Done deploy micro bosh (00:03:48)log writing failed. can't be called from trap context

Deployed `manifest.yml' to `Unknown Director', took 00:03:48 to complete
/Users/lexsys/.rvm/gems/ruby-2.0.0-p481/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `select': Bad file descriptor (Errno::EBADF)
  from /Users/lexsys/.rvm/gems/ruby-2.0.0-p481/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `io_select'
  from /Users/lexsys/.rvm/gems/ruby-2.0.0-p481/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:209:in `process'
  from /Users/lexsys/.rvm/gems/ruby-2.0.0-p481/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
  from /Users/lexsys/.rvm/gems/ruby-2.0.0-p481/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
  from /Users/lexsys/.rvm/gems/ruby-2.0.0-p481/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
  from /Users/lexsys/.rvm/gems/ruby-2.0.0-p481/gems/bosh_cli_plugin_micro-1.2768.0/lib/bosh/deployer/remote_tunnel.rb:43:in `block in monitor_session'
```

---
## manifest.yml

```
name: mkbosh

network:
  type: manual
  vip: 54.165.188.35
  ip: 10.0.0.6
  dns: [10.0.0.2]
  cloud_properties:
    subnet: subnet-f949d6c3

resources:
  persistent_disk: 20000
  cloud_properties:
    instance_type: t2.small
    availability_zone: us-east-1e

cloud:
  plugin: aws
  properties:
    aws:
      access_key_id: XXX
      secret_access_key: XXX
      default_key_name: bosh_lx
      default_security_groups: ["bosh_lx"]
      region: us-east-1
      ec2_private_key: ~/.ssh/bosh_lx.pem # Path relative to the manifest file

apply_spec:
  agent:
    blobstore: {address: 10.0.0.6}
    nats: {address: 10.0.0.6}
  properties:
    registry: {address: 10.0.0.6}
```

---

**$ gem list bosh**

```
*** LOCAL GEMS ***

bosh-bootstrap (0.14.4)
bosh-director-core (1.2768.0)
bosh-registry (1.2768.0)
bosh-stemcell (1.2768.0)
bosh-template (1.2768.0)
bosh_aws_cpi (1.2768.0)
bosh_cli (1.2768.0)
bosh_cli_plugin_micro (1.2768.0)
bosh_common (1.2768.0)
bosh_cpi (1.2768.0)
bosh_openstack_cpi (1.2768.0)
bosh_vcloud_cpi (0.7.1)
bosh_vsphere_cpi (1.2768.0)
```

---

**$ bosh status**

```
Config
             /Users/lexsys/.bosh_config

Director
  Name       mkbosh
  URL        https://54.165.188.35:25555
  Version    1.2776.0 (00000000)
  User       admin
  UUID       5f0b4717-622b-42ed-b38f-f4bf87566015
  CPI        aws
  dns        enabled (domain_name: microbosh)
  compiled_package_cache disabled
  snapshots  disabled

Deployment
  not set
```

---

stemcell version(s) you are using
`light-bosh-stemcell-2776-aws-xen-hvm-ubuntu-trusty-go_agent.tgz`
