### ISSUE TITLE
haproxy not start with static ip 

### ISSUE THREAD

**Issue by bkcisco** [cloudfoundry/bosh#703]
with a manifest file as below, got keep failing to start the haproxy 
can someone help what to assingn a static ip to haproxy[there is not floating ip available]

Started updating job common1 > common1/0
  Started updating job postgres > postgres/0
  Started updating job haproxy > haproxy/0
  Started updating job router > router/0
  Started updating job controller > controller/0
  Started updating job dea
  Started updating job dea > dea/0
  Started updating job dea > dea/1
  Started updating job dea > dea/3
  Started updating job dea > dea/2
     Done updating job dea > dea/3 (00:01:26)
     Done updating job dea > dea/1 (00:01:48)
     Done updating job dea > dea/0 (00:02:12)
     Done updating job postgres > postgres/0 (00:02:35)
     Done updating job dea > dea/2 (00:02:41)
     Done updating job dea (00:02:41)
     Done updating job router > router/0 (00:03:28)
     Done updating job common1 > common1/0 (00:05:01)
   Failed updating job haproxy > haproxy/0: `haproxy/0' is not running after update (00:10:10)

```
<%
director_uuid = "dd68d91f-8911-461d-b108-2051ff768862"
protocol = "https"
deployment_name = 'mb-lab'
cf_release = "176"
static_ip= "172.28.132.239"
common_password = "ciscotxbu"
root_domain = "mb-lab.huron.uno"
%>

---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
 - name: cf
   version: <%= cf_release %>

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.large

update:
  canaries: 0
  canary_watch_time: 30000-600000
  update_watch_time: 30000-600000
  max_in_flight: 32
  serial: false

networks:
  - name: default
    type: dynamic
    cloud_properties:
      # Create a new network for CF servers and use that uuid
      #name: public
      net_id: b0c9450f-b5be-481d-9b90-779109f951f4
      security_groups:
        - default

  - name: manual
    type: manual
    subnets:
      - range: 172.28.132.0/24
        gateway: 172.28.132.1
        static:
          - 172.28.132.224 - 172.28.132.249
        reserved:
          - 172.28.132.2 - 172.28.132.128
        dns:
          -  171.70.168.183
        cloud_properties:
          net_id: b0c9450f-b5be-481d-9b90-779109f951f4
          security_groups:
            - default

resource_pools:
  - name: small
    network: default
    size: 4
    stemcell:
      name: bosh-openstack-kvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m1.small

  - name: medium
    network: default
    size: 1
    stemcell:
      name: bosh-openstack-kvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m1.small

  - name: large
    network: default
    size: 4
    stemcell:
      name: bosh-openstack-kvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: cf-dea

jobs:
  - name: common1
    templates:
      - name: nats
      - name: nats_stream_forwarder
      - name: syslog_aggregator
      - name: debian_nfs_server
      - name: loggregator
      - name: uaa
    instances: 1
    resource_pool: medium
    persistent_disk: 30000
    networks:
      - name: default
        default: [dns, gateway]

  - name: postgres
    templates:
      - name: postgres
    instances: 1
    resource_pool: small
    persistent_disk: 10000
    networks:
      - name: default
        default: [dns, gateway]
    properties:
      db: databases

  - name: controller
    templates:
      - name: loggregator_trafficcontroller
      - name: cloud_controller_ng
      - name: cloud_controller_worker
      - name: cloud_controller_clock
    instances: 1
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]
 #   properties:
 #     ccdb: ccdb

  - name: dea
    templates:
      - name: dea_logging_agent
      - name: dea_next
    instances: 4
    resource_pool: large
    networks:
      - name: default
        default: [dns, gateway]

  - name: router
    templates:
      - name: gorouter
      - name: etcd
      - name: hm9000
    instances: 1
    persistent_disk: 10000
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]

  - name: haproxy
    templates:
      - name: haproxy
    instances: 1
    resource_pool: small
    networks:
#      - name: default
#        default: [dns, gateway]
      - name: manual
        default: [dns, gateway]
        static_ips:
          - <%= static_ip %>
    properties:
      networks:
        apps: manual 

properties:
  domain: <%= root_domain %>
  system_domain: <%= root_domain %>
  system_domain_organization: 'admin'
  app_domains:
    - <%= root_domain %>

  # Below is used by templates to pull in the network config
  networks:
    apps: default

...snip...
```
