### ISSUE TITLE
Unused property template_only.aws.availability_zone

### ISSUE THREAD

**Issue by karlkfi** [cloudfoundry/bosh#773]
What is this template_only.aws.availability_zone for? It seems to be generated by the aws plugin, but bosh doesn't seem to USE it anywhere...

Can it be nuked?

```
properties:
  template_only:
    aws:
      availability_zone: <%= availability_zone %>
```

https://github.com/cloudfoundry/bosh/blob/master/bosh_cli_plugin_aws/templates/bosh.yml.erb#L87
