### ISSUE TITLE
a deploy problem whe i configed resource_pools.cloud_properties:availability_zone;

### ISSUE THREAD

**Issue by guanglinlv** [cloudfoundry/bosh#782]
hi ,

whe i try to deploy bosh/cf/diego etc,i get a error likes `"Invalid input received: Availability zone szxy01-az is invalid"` when create a volume;

here is the config:

```yml
resource_pools:
  - name: common
    network: default
    size: 8
    stemcell:
      name: bosh-openstack-kvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m1.small 
      availability_zone: szxy01-az
jobs:
  - name: postgres
    template: postgres
    instances: 1
    resource_pool: common
    persistent_disk: 16384    # any needed persistent_disk jobs will get the deploy error;
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.10.10.122
```

in my openstack environment,the VM instace availability_zone is `szxy01-az` but the persistent_disk is different,it's `nova`,i'm not sure why it use `szxy01-az` to create volume.

can i specify the availability_zone for volume not instance ?

any help or answers? thanks.

BEST
guanglinLv
