### ISSUE TITLE
Is there any difference or attention on microbosh manifest between openstack-kvm-ubuntu and openstack-kvm-centos

### ISSUE THREAD

**Issue by guanglinlv** [cloudfoundry/bosh#791]
Hi all,

I'm try to deploy micro bosh use `bosh-stemcell-2881-openstack-kvm-centos-go_agent-raw`, but i got some strange errors #788 ,  following is my `microbosh.yml` that i had used it deploy microbosh with stemcell `bosh-stemcell-2881-openstack-kvm-ubuntu-go_agent-raw` successfully.

microbosh.yml:

```yml
---
name: microbosh

logging:
  # If needed increase the default logging level to trace REST traffic with IaaS providers. Default is info
  level: debug
  # Default location is <deployment_dir>/bosh_micro_deploy.log
  # file :

network:
  type: manual 
  vip: 10.63.50.82  #float IP you apply for micro bosh
  ip: 192.168.2.3
  cloud_properties:
    net_id: bd60312e-246b-40eb-b3b9-b91d27a921de  #net_id of your VM
resources:
  persistent_disk: 20480 #it is very important,the volume size  connect to VM 
  cloud_properties:
    instance_type: m1.medium
    availability_zone: szxts01-az

cloud:
  plugin: openstack
  properties:
    openstack:
      auth_url: http://10.63.49.40:5000/v2.0   #change it with your openstack ip
      username: lvguanglin   #openstack username
      api_key: lvguanglin   #openstack password
      tenant: CloudFoundry01     #the project of openstack
#      region: RegionOne
      default_security_groups: ["default", "default"]
      default_key_name: lv_microbosh
      private_key: /root/.ssh/lv_microbosh.pem   #change it with your keypair route.
      ignore_server_availability_zone: true

apply_spec:
  properties:
    director:
      max_threads: 3
    hm:
      resurrector_enabled: true
    ntp:
      - 0.north-america.pool.ntp.org
      - 1.north-america.pool.ntp.org
```

Is there any more configuration for `bosh-stemcell-2881-openstack-kvm-centos-go_agent-raw` ?

thanks.
