### ISSUE TITLE
Static IP calculation fails?

### ISSUE THREAD

**Issue by Nopik** [cloudfoundry/bosh#811]
I have this working deployment network configuration:

```
jobs:
  - name: foo
    instances: 1
    networks:
      - name: foo
        static_ips: [10.244.9.2]
networks:
  - name: foo
    subnets:
      - range: 10.244.9.0/30
        reserved: [10.244.9.1]
        static: [10.244.9.2]
        cloud_properties: {}
      - range: 10.244.9.4/30
        reserved: [10.244.9.5]
        static: [10.244.9.6]
        cloud_properties: {}

```

When I change job to:

```
jobs:
  - name: foo
    instances: 2
    networks:
      - name: foo
        static_ips: [10.244.9.2 10.244.9.6]
```

deployment fails with this error:

```
Error 100: 10.244.9.6 contains '1' bits within the host portion of the netmask.
```

I'm not 100% sure if I specify static_ips correctly, but if I do, then error is completely off.
