### ISSUE TITLE
[aws] bosh deploy is showing a diff in resource pools: ephemeral_disk.instance_type

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#917]
(from v3033)

I think an internal attribute of a resource pool - `cloud_properties.ephemeral_disk.instance_type` is being exposed during `bosh deploy` - and the result is that we are being forced to redeploy all VMs again as bosh thinks there is a difference.

From cf-release there is no mention of this new field:

```yaml
  - name: router_z2
    cloud_properties:
      instance_type: c4.2xlarge
      ephemeral_disk:
        size: 10_240
        type: gp2
```

But when we deploy, we see a diff that triggers a recreation of all these VMs each time.

```
router_z2
  cloud_properties
    ephemeral_disk
      - instance_type: c4.2xlarge
```

This is forcing us to fork the cf-release templates in the meantime to add the duplicate piece of configuration:

```yaml
  - name: router_z2
    cloud_properties:
      instance_type: c4.2xlarge
      ephemeral_disk:
        size: 10_240
        type: gp2
        instance_type: c4.2xlarge
```

(last line is the redundant additional line we need to add to templates)
